//   *****************************************************************************************************************************************
//   ****   PLEASE NOTE: This is a READ-ONLY representation of the actual script. For editing please press the "Develop Script" button.   ****
//   *****************************************************************************************************************************************

Action()
{
	truclient_step("1", "Evaluate JavaScript code Utils.addAutoHeader('App...ency URL', true)", "snapshot=Action_1.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC00_Launch Agency URL");
	truclient_step("2", "Navigate to 'https://av-pt-ferrari.accela.com/'", "snapshot=Action_2.inf");
	truclient_step("3", "Wait until [object HTMLParagraphElem... decorator exists", "snapshot=Action_3.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC00_Launch Agency URL",0);
	truclient_step("4", "Wait 2 seconds", "snapshot=Action_4.inf");
	truclient_step("5", "Evaluate JavaScript code Utils.addAutoHeader('App...01_Login', true)", "snapshot=Action_5.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC01_Login");
	truclient_step("6", "Login", "snapshot=Action_6.inf");
	{
		truclient_step("6.1", "Type TC.getParam('Agency') in Agency textbox", "snapshot=Action_6.1.inf");
		truclient_step("6.3", "Type TC.getParam('UserName') in User Name textbox", "snapshot=Action_6.3.inf");
		truclient_step("6.5", "Type ****************** in Password passwordbox", "snapshot=Action_6.5.inf");
		truclient_step("6.6", "Press key Enter on Password passwordbox", "snapshot=Action_6.6.inf");
	}
	truclient_step("7", "Call Function AV2.NewUI", "snapshot=Action_7.inf");
	truclient_step("8", "Wait until Button exists", "snapshot=Action_8.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC01_Login",0);
	truclient_step("9", "Wait 2 seconds", "snapshot=Action_9.inf");
	truclient_step("10", "Click on Button", "snapshot=Action_10.inf");
	truclient_step("11", "Wait until TC.getParam('RecordId') exists", "snapshot=Action_11.inf");
	truclient_step("12", "Click on TC.getParam('RecordId')", "snapshot=Action_12.inf");
	truclient_step("13", "Evaluate JavaScript code [Code]", "snapshot=Action_13.inf");
	truclient_step("14", "Wait until Record # exists", "snapshot=Action_14.inf");
	truclient_step("15", "Evaluate JavaScript code Utils.addAutoHeader('App... Search', true)", "snapshot=Action_15.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC02_Record search_Click Record  Search");
	truclient_step("16", "Click on Refine Search link", "snapshot=Action_16.inf");
	truclient_step("17", "Wait until Cancel link exists", "snapshot=Action_17.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC02_Record search_Click Record  Search",0);
	truclient_step("18", "Wait 2 seconds", "snapshot=Action_18.inf");
	truclient_step("19", "Click on Cancel link", "snapshot=Action_19.inf");
	truclient_step("20", "Click on New", "snapshot=Action_20.inf");
	truclient_step("21", "Activate browser window #2", "snapshot=Action_21.inf");
	truclient_step("22", "Activate tab 1", "snapshot=Action_22.inf");
	truclient_step("23", "Close Tab active tab", "snapshot=Action_23.inf");
	truclient_step("24", "Activate browser window #1", "snapshot=Action_24.inf");
	truclient_step("25", "Wait 2 seconds", "snapshot=Action_25.inf");
	truclient_step("26", "Click on TC.getParam('RecordId') link", "snapshot=Action_26.inf");
	truclient_step("27", "Evaluate JavaScript code Utils.addAutoHeader('App...ord link', true)", "snapshot=Action_27.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC03_Record Detail_Click Record link");
	truclient_step("28", "Click on Record link", "snapshot=Action_28.inf");
	truclient_step("29", "Wait until Record # label exists", "snapshot=Action_29.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC03_Record Detail_Click Record link",0);
	truclient_step("30", "Wait 2 seconds", "snapshot=Action_30.inf");
	truclient_step("31", "Click on Menu Save Reset Summary...", "snapshot=Action_31.inf");
	truclient_step("32", "Click on Address link", "snapshot=Action_32.inf");
	truclient_step("33", "Evaluate JavaScript code Utils.addAutoHeader('App...d select', true)", "snapshot=Action_33.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC04_Address search_Click Search and select");
	truclient_step("34", "Click on Search and Select link", "snapshot=Action_34.inf");
	truclient_step("35", "Wait until Cancel link exists", "snapshot=Action_35.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC04_Address search_Click Search and select",0);
	truclient_step("36", "Wait 2 seconds", "snapshot=Action_36.inf");
	truclient_step("37", "Click on Cancel link", "snapshot=Action_37.inf");
	truclient_step("38", "Evaluate JavaScript code Utils.addAutoHeader('App...Address)', true)", "snapshot=Action_38.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC05_Address lookup_Click  lookup link(Address)");
	truclient_step("39", "Click on Look Up link", "snapshot=Action_39.inf");
	truclient_step("40", "Wait until Cancel link exists", "snapshot=Action_40.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC05_Address lookup_Click  lookup link(Address)",0);
	truclient_step("41", "Wait 2 seconds", "snapshot=Action_41.inf");
	truclient_step("42", "Click on Cancel link", "snapshot=Action_42.inf");
	truclient_step("43", "Click on Menu New Delete Look...", "snapshot=Action_43.inf");
	truclient_step("44", "Click on TC.getParam('Parcel') link", "snapshot=Action_44.inf");
	truclient_step("45", "Click on Cancel link", "snapshot=Action_45.inf");
	truclient_step("46", "Wait 2 seconds", "snapshot=Action_46.inf");
	truclient_step("47", "Click on Summary Record Custom...", "snapshot=Action_47.inf");
	truclient_step("48", "Wait until Parcel link exists", "snapshot=Action_48.inf");
	truclient_step("49", "Click on Parcel link", "snapshot=Action_49.inf");
	truclient_step("50", "Evaluate JavaScript code Utils.addAutoHeader('App...d Select', true)", "snapshot=Action_50.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC09_Parcel Search_Click Search and Select");
	truclient_step("51", "Click on Search and Select link", "snapshot=Action_51.inf");
	truclient_step("52", "Wait until Cancel link exists", "snapshot=Action_52.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC09_Parcel Search_Click Search and Select",0);
	truclient_step("53", "Wait 2 seconds", "snapshot=Action_53.inf");
	truclient_step("54", "Click on Cancel link", "snapshot=Action_54.inf");
	truclient_step("55", "Evaluate JavaScript code Utils.addAutoHeader('App...k Lookup', true)", "snapshot=Action_55.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC10_Parcel Search Lookup_Click Lookup");
	truclient_step("56", "Click on Look Up link", "snapshot=Action_56.inf");
	truclient_step("57", "Wait until Cancel link exists", "snapshot=Action_57.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC10_Parcel Search Lookup_Click Lookup",0);
	truclient_step("58", "Wait 2 seconds", "snapshot=Action_58.inf");
	truclient_step("59", "Click on Cancel link", "snapshot=Action_59.inf");
	truclient_step("60", "Wait until New link exists", "snapshot=Action_60.inf");
	truclient_step("61", "Evaluate JavaScript code Utils.addAutoHeader('App...rcel New', true)", "snapshot=Action_61.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC11_Owner New_Click Parcel New");
	truclient_step("62", "Click on New link", "snapshot=Action_62.inf");
	truclient_step("63", "Wait until Cancel link exists", "snapshot=Action_63.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC11_Owner New_Click Parcel New",0);
	truclient_step("64", "Wait 2 seconds", "snapshot=Action_64.inf");
	truclient_step("65", "Wait until Cancel link exists", "snapshot=Action_65.inf");
	truclient_step("66", "Click on Cancel link", "snapshot=Action_66.inf");
	truclient_step("67", "Click on TC.getParam('Owner') link", "snapshot=Action_67.inf");
	truclient_step("68", "Click on Cancel link", "snapshot=Action_68.inf");
	truclient_step("69", "Click on Owner Parcel Payment...", "snapshot=Action_69.inf");
	truclient_step("70", "Wait until Owner link exists", "snapshot=Action_70.inf");
	truclient_step("71", "Click on Owner link", "snapshot=Action_71.inf");
	truclient_step("72", "Wait until Primary link exists", "snapshot=Action_72.inf");
	truclient_step("73", "Click on TC.getParam('Owner') link", "snapshot=Action_73.inf");
	truclient_step("74", "Click on Menu Submit Synchronize...", "snapshot=Action_74.inf");
	truclient_step("75", "Click on Cancel link", "snapshot=Action_75.inf");
	truclient_step("76", "Evaluate JavaScript code Utils.addAutoHeader('App...k LookUp', true)", "snapshot=Action_76.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC12_Owner Search Lookup_Click LookUp");
	truclient_step("77", "Click on Look Up link", "snapshot=Action_77.inf");
	truclient_step("78", "Wait until Reference Owner Search... gridcell exists", "snapshot=Action_78.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC12_Owner Search Lookup_Click LookUp",0);
	truclient_step("79", "Wait 2 seconds", "snapshot=Action_79.inf");
	truclient_step("80", "Click on Cancel link", "snapshot=Action_80.inf");
	truclient_step("81", "Evaluate JavaScript code Utils.addAutoHeader('App...lick New', true)", "snapshot=Action_81.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC13_Owner New_Click New");
	truclient_step("82", "Click on New link", "snapshot=Action_82.inf");
	truclient_step("83", "Wait until Cancel link exists", "snapshot=Action_83.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC13_Owner New_Click New",0);
	truclient_step("84", "Wait 2 seconds", "snapshot=Action_84.inf");
	truclient_step("85", "Click on Cancel link", "snapshot=Action_85.inf");
	truclient_step("86", "Evaluate JavaScript code Utils.addAutoHeader('App...(Record)', true)", "snapshot=Action_86.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC06_Record status_Click Status(Record)");
	truclient_step("87", "Click on Status link", "snapshot=Action_87.inf");
	truclient_step("88", "Wait until Status Date label exists", "snapshot=Action_88.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC06_Record status_Click Status(Record)",0);
	truclient_step("89", "Wait 2 seconds", "snapshot=Action_89.inf");
	truclient_step("90", "Click on Menu Save Reset Help...", "snapshot=Action_90.inf");
	truclient_step("91", "Evaluate JavaScript code Utils.addAutoHeader('App...istrory)', true)", "snapshot=Action_91.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC07_Record status History_Click Status History (Application Histrory)");
	truclient_step("92", "Click on Application History link", "snapshot=Action_92.inf");
	truclient_step("93", "Wait until Status Date columnheader exists", "snapshot=Action_93.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC07_Record status History_Click Status History (Application Histrory)",0);
	truclient_step("94", "Wait 2 seconds", "snapshot=Action_94.inf");
	truclient_step("95", "Evaluate JavaScript code Utils.addAutoHeader('App...istrory)', true)", "snapshot=Action_95.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC08_Record status History_Click Status History Search(Application Histrory)");
	truclient_step("96", "Click on Search link", "snapshot=Action_96.inf");
	truclient_step("97", "Wait until Cancel link exists", "snapshot=Action_97.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC08_Record status History_Click Status History Search(Application Histrory)",0);
	truclient_step("98", "Wait 2 seconds", "snapshot=Action_98.inf");
	truclient_step("99", "Wait until Status Date gridcell exists", "snapshot=Action_99.inf");
	truclient_step("100", "Click on Cancel link", "snapshot=Action_100.inf");
	truclient_step("101", "Wait 2 seconds", "snapshot=Action_101.inf");
	truclient_step("102", "Click on Parcel Payment Payment...", "snapshot=Action_102.inf");
	truclient_step("103", "Click on Documents link", "snapshot=Action_103.inf");
	truclient_step("104", "Evaluate JavaScript code Utils.addAutoHeader('App... record)', true)", "snapshot=Action_104.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC14_Documents LookUp_Select Info from Manage Documents Lookup(default record)");
	truclient_step("105", "Click on Look Up", "snapshot=Action_105.inf");
	truclient_step("106", "Wait until Cancel link exists", "snapshot=Action_106.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC14_Documents LookUp_Select Info from Manage Documents Lookup(default record)",0);
	truclient_step("107", "Wait 2 seconds", "snapshot=Action_107.inf");
	truclient_step("108", "Click on Cancel link", "snapshot=Action_108.inf");
	truclient_step("109", "Evaluate JavaScript code Utils.addAutoHeader('App...ocuments', true)", "snapshot=Action_109.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC15_Documents_Click Documents");
	truclient_step("110", "Click on New link", "snapshot=Action_110.inf");
	truclient_step("111", "Wait until Cancel link exists", "snapshot=Action_111.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC15_Documents_Click Documents",0);
	truclient_step("112", "Wait 2 seconds", "snapshot=Action_112.inf");
	truclient_step("113", "Click on Cancel link", "snapshot=Action_113.inf");
	truclient_step("114", "Wait 2 seconds", "snapshot=Action_114.inf");
	truclient_step("115", "Click on Contacts Documents ...", "snapshot=Action_115.inf");
	truclient_step("116", "Click on Contacts link", "snapshot=Action_116.inf");
	truclient_step("117", "Wait 2 seconds", "snapshot=Action_117.inf");
	truclient_step("118", "Click on Manage Contacts JavaScript link", "snapshot=Action_118.inf");
	truclient_step("119", "Wait until 1 Contact No. Primary... exists", "snapshot=Action_119.inf");
	truclient_step("120", "Evaluate JavaScript code Utils.addAutoHeader('App... Contact', true)", "snapshot=Action_120.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC16_LookUpContacts_Select LookUp Contact");
	truclient_step("121", "Click on Look Up Contact link", "snapshot=Action_121.inf");
	truclient_step("122", "Wait until Cancel link exists", "snapshot=Action_122.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC16_LookUpContacts_Select LookUp Contact",0);
	truclient_step("123", "Wait 2 seconds", "snapshot=Action_123.inf");
	truclient_step("124", "Click on Cancel link", "snapshot=Action_124.inf");
	truclient_step("125", "Evaluate JavaScript code Utils.addAutoHeader('App...er(Type)', true)", "snapshot=Action_125.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC17_Contacts Type_Click Contacts Number(Type)");
	truclient_step("126", "Click on TC.getParam('ContactNumber') link", "snapshot=Action_126.inf");
	truclient_step("127", "Wait until Contact Address exists", "snapshot=Action_127.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC17_Contacts Type_Click Contacts Number(Type)",0);
	truclient_step("128", "Wait 2 seconds", "snapshot=Action_128.inf");
	truclient_step("129", "Click on Menu Save Reset Cancel...", "snapshot=Action_129.inf");
	truclient_step("130", "Evaluate JavaScript code Utils.addAutoHeader('App...ddressID', true)", "snapshot=Action_130.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC18_ContactsAddress_Click ContactsAddressID");
	truclient_step("131", "Click on TC.getParam('ContactAddressID')", "snapshot=Action_131.inf");
	truclient_step("132", "Wait until Cancel link exists", "snapshot=Action_132.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC18_ContactsAddress_Click ContactsAddressID",0);
	truclient_step("133", "Wait 2 seconds", "snapshot=Action_133.inf");
	truclient_step("134", "Wait until Menu JavaScript link exists", "snapshot=Action_134.inf");
	truclient_step("135", "Close Tab active tab", "snapshot=Action_135.inf");
	truclient_step("136", "Activate browser window #2", "snapshot=Action_136.inf");
	truclient_step("137", "Activate tab 1", "snapshot=Action_137.inf");
	truclient_step("138", "Wait until Address Type label exists", "snapshot=Action_138.inf");
	truclient_step("139", "Click on Cancel", "snapshot=Action_139.inf");
	truclient_step("140", "Wait 2 seconds", "snapshot=Action_140.inf");
	truclient_step("141", "Activate browser window #1", "snapshot=Action_141.inf");
	truclient_step("142", "Evaluate JavaScript code Utils.addAutoHeader('App...ookUpNew', true)", "snapshot=Action_142.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC19_Contacts Address LookUp_Click Contacts Address LookUpNew");
	truclient_step("143", "Click on New JavaScript link", "snapshot=Action_143.inf");
	truclient_step("144", "Wait until Cancel exists", "snapshot=Action_144.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC19_Contacts Address LookUp_Click Contacts Address LookUpNew",0);
	truclient_step("145", "Wait 2 seconds", "snapshot=Action_145.inf");
	truclient_step("146", "Close Tab active tab", "snapshot=Action_146.inf");
	truclient_step("147", "Click on Cancel link", "snapshot=Action_147.inf");
	truclient_step("148", "Click on Cancel link", "snapshot=Action_148.inf");
	truclient_step("149", "Click on New link", "snapshot=Action_149.inf");
	truclient_step("150", "Click on Cancel link", "snapshot=Action_150.inf");
	truclient_step("151", "Wait until Inspections link exists", "snapshot=Action_151.inf");
	truclient_step("152", "Click on Inspections link", "snapshot=Action_152.inf");
	truclient_step("153", "Evaluate JavaScript code Utils.addAutoHeader('App...s Search', true)", "snapshot=Action_153.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC20_Inspections Search_Click On Inspections Search");
	truclient_step("154", "Click on Search link", "snapshot=Action_154.inf");
	truclient_step("155", "Wait until Cancel link exists", "snapshot=Action_155.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC20_Inspections Search_Click On Inspections Search",0);
	truclient_step("156", "Wait 2 seconds", "snapshot=Action_156.inf");
	truclient_step("157", "Click on Cancel link", "snapshot=Action_157.inf");
	truclient_step("158", "Wait until Inspection Type link exists", "snapshot=Action_158.inf");
	truclient_step("159", "Evaluate JavaScript code Utils.addAutoHeader('App...ype link', true)", "snapshot=Action_159.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC21_Inspection Record Detail_Click On Inspection Type link");
	truclient_step("160", "Click on TC.getParam('InspectionType') link", "snapshot=Action_160.inf");
	truclient_step("161", "Wait until Cancel link exists", "snapshot=Action_161.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC21_Inspection Record Detail_Click On Inspection Type link",0);
	truclient_step("162", "Wait 2 seconds", "snapshot=Action_162.inf");
	truclient_step("163", "Click on Cancel link", "snapshot=Action_163.inf");
	truclient_step("164", "Wait until Professionals link exists", "snapshot=Action_164.inf");
	truclient_step("165", "Click on Professionals link", "snapshot=Action_165.inf");
	truclient_step("166", "Evaluate JavaScript code Utils.addAutoHeader('App...kUp link', true)", "snapshot=Action_166.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC22_Professionals LookUp_Click On LookUp link");
	truclient_step("167", "Click on Look Up link", "snapshot=Action_167.inf");
	truclient_step("168", "Wait until Cancel link exists", "snapshot=Action_168.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC22_Professionals LookUp_Click On LookUp link",0);
	truclient_step("169", "Wait 2 seconds", "snapshot=Action_169.inf");
	truclient_step("170", "Click on Cancel link", "snapshot=Action_170.inf");
	truclient_step("171", "Wait until License Type link exists", "snapshot=Action_171.inf");
	truclient_step("172", "Evaluate JavaScript code Utils.addAutoHeader('App...nals New', true)", "snapshot=Action_172.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC23_Professionals New_Click Professionals New");
	truclient_step("173", "Click on New link", "snapshot=Action_173.inf");
	truclient_step("174", "Wait until Cancel link exists", "snapshot=Action_174.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC23_Professionals New_Click Professionals New",0);
	truclient_step("175", "Wait 2 seconds", "snapshot=Action_175.inf");
	truclient_step("176", "Click on Cancel link", "snapshot=Action_176.inf");
	truclient_step("177", "Wait until Reference License ID label exists", "snapshot=Action_177.inf");
	truclient_step("178", "Wait until License # link exists", "snapshot=Action_178.inf");
	truclient_step("179", "Evaluate JavaScript code Utils.addAutoHeader('App...s Detail', true)", "snapshot=Action_179.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC24_Professionals New_Click Professionals Detail");
	truclient_step("180", "Click on TC.getParam('ProfessinalsNew') link", "snapshot=Action_180.inf");
	truclient_step("181", "Wait until Cancel link exists", "snapshot=Action_181.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC24_Professionals New_Click Professionals Detail",0);
	truclient_step("182", "Wait 2 seconds", "snapshot=Action_182.inf");
	truclient_step("183", "Click on Cancel link", "snapshot=Action_183.inf");
	truclient_step("184", "Wait 2 seconds", "snapshot=Action_184.inf");
	truclient_step("185", "Click on Workflow link", "snapshot=Action_185.inf");
	truclient_step("186", "Evaluate JavaScript code Utils.addAutoHeader('App...New Link', true)", "snapshot=Action_186.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC25_WorkflowNew_Click On WorkflowNew Link");
	truclient_step("187", "Click on New link", "snapshot=Action_187.inf");
	truclient_step("188", "Wait until Cancel link exists", "snapshot=Action_188.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC25_WorkflowNew_Click On WorkflowNew Link",0);
	truclient_step("189", "Wait 2 seconds", "snapshot=Action_189.inf");
	truclient_step("190", "Click on Cancel link", "snapshot=Action_190.inf");
	truclient_step("191", "Evaluate JavaScript code Utils.addAutoHeader('App...ory Link', true)", "snapshot=Action_191.inf");
	lr_start_transaction("Ferrari UI Forms_AA_MILARA_TC26_WorkflowNew_Click On Workflow History Link");
	truclient_step("192", "Click on Workflow History link", "snapshot=Action_192.inf");
	truclient_step("193", "Wait until Task link exists", "snapshot=Action_193.inf");
	lr_end_transaction("Ferrari UI Forms_AA_MILARA_TC26_WorkflowNew_Click On Workflow History Link",0);
	truclient_step("194", "Wait 2 seconds", "snapshot=Action_194.inf");
	truclient_step("195", "Click on Parcel Payment Payment...", "snapshot=Action_195.inf");
	truclient_step("196", "Click on element (3)", "snapshot=Action_196.inf");
	truclient_step("197", "Click on Administration link", "snapshot=Action_197.inf");
	truclient_step("198", "Wait 2 seconds", "snapshot=Action_198.inf");
	truclient_step("199", "Click on Agency Profile", "snapshot=Action_199.inf");
	truclient_step("200", "Wait until Form Portlet Designer exists", "snapshot=Action_200.inf");
	truclient_step("201", "Click on Form Portlet Designer link", "snapshot=Action_201.inf");
	truclient_step("202", "Wait 2 seconds", "snapshot=Action_202.inf");
	truclient_step("203", "Select Single Entry Address Form from Portlet listbox", "snapshot=Action_203.inf");
	truclient_step("204", "Wait until Single Entry Address Form gridcell exists", "snapshot=Action_204.inf");
	truclient_step("205", "Evaluate JavaScript code Utils.addAutoHeader('App...m Detail', true)", "snapshot=Action_205.inf");
	truclient_step("206", "Click on SOM Single Entry Address... link", "snapshot=Action_206.inf");
	truclient_step("207", "Activate browser window #2", "snapshot=Action_207.inf");
	truclient_step("208", "Activate tab 1", "snapshot=Action_208.inf");
	truclient_step("209", "Click on OK button", "snapshot=Action_209.inf");
	truclient_step("211", "Close Tab active tab", "snapshot=Action_211.inf");
	truclient_step("212", "Wait until Cancel exists", "snapshot=Action_212.inf");
	truclient_step("213", "Wait 2 seconds", "snapshot=Action_213.inf");
	truclient_step("214", "Activate browser window #1", "snapshot=Action_214.inf");
	truclient_step("220", "Click on Cancel", "snapshot=Action_220.inf");
	truclient_step("221", "Wait 2 seconds", "snapshot=Action_221.inf");
	truclient_step("222", "Select Single Entry Parcel Form from Portlet listbox", "snapshot=Action_222.inf");
	truclient_step("223", "Wait until Single Entry Parcel Form link exists", "snapshot=Action_223.inf");
	truclient_step("224", "Evaluate JavaScript code Utils.addAutoHeader('App... Details', true)", "snapshot=Action_224.inf");
	truclient_step("225", "Click on Single Entry Parcel Form link", "snapshot=Action_225.inf");
	truclient_step("230", "Close Tab active tab", "snapshot=Action_230.inf");
	truclient_step("231", "Click on OK button", "snapshot=Action_231.inf");
	truclient_step("232", "Wait until Cancel link exists", "snapshot=Action_232.inf");
	truclient_step("233", "Wait 2 seconds", "snapshot=Action_233.inf");
	truclient_step("234", "Close Tab active tab", "snapshot=Action_234.inf");
	truclient_step("253", "Click on Save", "snapshot=Action_253.inf");
	truclient_step("255", "Scroll on within your browser....", "snapshot=Action_255.inf");
	truclient_step("256", "Scroll on within your browser....", "snapshot=Action_256.inf");
	truclient_step("257", "Scroll on within your browser....", "snapshot=Action_257.inf");
	truclient_step("258", "Scroll on within your browser....", "snapshot=Action_258.inf");
	truclient_step("262", "Click on Cancel", "snapshot=Action_262.inf");
	truclient_step("263", "Wait 2 seconds", "snapshot=Action_263.inf");
	truclient_step("264", "Select Single Entry Owner Form from Portlet listbox", "snapshot=Action_264.inf");
	truclient_step("265", "Wait until Single Entry Owner Form gridcell exists", "snapshot=Action_265.inf");
	truclient_step("266", "Evaluate JavaScript code Utils.addAutoHeader('App... Details', true)", "snapshot=Action_266.inf");
	truclient_step("267", "Click on Single Entry Owner Form gridcell", "snapshot=Action_267.inf");
	truclient_step("268", "Close Tab active tab", "snapshot=Action_268.inf");
	truclient_step("269", "Click on OK button", "snapshot=Action_269.inf");
	truclient_step("270", "Wait until Cancel exists", "snapshot=Action_270.inf");
	truclient_step("271", "Wait 2 seconds", "snapshot=Action_271.inf");
	truclient_step("272", "Activate browser window #2", "snapshot=Action_272.inf");
	truclient_step("273", "Activate tab 1", "snapshot=Action_273.inf");
	truclient_step("276", "Close Tab active tab", "snapshot=Action_276.inf");
	truclient_step("277", "Activate browser window #1", "snapshot=Action_277.inf");
	truclient_step("291", "Scroll on within your browser....", "snapshot=Action_291.inf");
	truclient_step("292", "Scroll on within your browser....", "snapshot=Action_292.inf");
	truclient_step("303", "Click on Cancel", "snapshot=Action_303.inf");
	truclient_step("304", "Click on element (3)", "snapshot=Action_304.inf");
	truclient_step("305", "Wait 2 seconds", "snapshot=Action_305.inf");
	truclient_step("306", "Click on Exit Administration link", "snapshot=Action_306.inf");
	truclient_step("307", "Evaluate JavaScript code Utils.addAutoHeader('App...Sign Out', true)", "snapshot=Action_307.inf");
	truclient_step("308", "Click on element (3)", "snapshot=Action_308.inf");
	truclient_step("309", "Click on Sign Out link", "snapshot=Action_309.inf");
	truclient_step("310", "Wait until You have successfully... exists", "snapshot=Action_310.inf");

	return 0;
}
