//   *****************************************************************************************************************************************
//   ****   PLEASE NOTE: This is a READ-ONLY representation of the actual script. For editing please press the "Develop Script" button.   ****
//   *****************************************************************************************************************************************

Action()
{
	truclient_step("1", "Evaluate JavaScript code Utils.addAutoHeader('App...A_Launch', true)", "snapshot=Action_1.inf");
	truclient_step("2", "Evaluate JavaScript code Utils.addAutoHeader", "snapshot=Action_2.inf");
	truclient_step("3", "Navigate to 'https://av-pt-ferrari.accela.com/'", "snapshot=Action_3.inf");
	lr_start_transaction("GIS_AA_Launch");
	truclient_step("4", "Navigate to 'https://av-pt-ferrari.accela.com/'", "snapshot=Action_4.inf");
	truclient_step("5", "Wait until [object HTMLParagraphElem... decorator exists", "snapshot=Action_5.inf");
	lr_end_transaction("GIS_AA_Launch",0);
	truclient_step("6", "Wait 2 seconds", "snapshot=Action_6.inf");
	truclient_step("7", "Evaluate JavaScript code Utils.addAutoHeader('App...AA_Login', true)", "snapshot=Action_7.inf");
	lr_start_transaction("GIS_AA_Login");
	truclient_step("8", "Login", "snapshot=Action_8.inf");
	{
		truclient_step("8.1", "Type OSCEOLA in Agency textbox", "snapshot=Action_8.1.inf");
		truclient_step("8.2", "Type admin in admin textbox", "snapshot=Action_8.2.inf");
		truclient_step("8.3", "Type ***** in password passwordbox", "snapshot=Action_8.3.inf");
		truclient_step("8.4", "Click on Login button", "snapshot=Action_8.4.inf");
	}
	truclient_step("9", "Wait until focusable (1) exists", "snapshot=Action_9.inf");
	lr_end_transaction("GIS_AA_Login",0);
	truclient_step("10", "Wait 2 seconds", "snapshot=Action_10.inf");
	truclient_step("11", "Click on focusable (1)", "snapshot=Action_11.inf");
	truclient_step("12", "Wait 2 seconds", "snapshot=Action_12.inf");
	truclient_step("13", "Wait until Map exists", "snapshot=Action_13.inf");
	truclient_step("15", "Click on Map", "snapshot=Action_15.inf");
	truclient_step("17", "Wait 2 seconds", "snapshot=Action_17.inf");
	truclient_step("18", "Wait until Search Addresses, Parcels textbox exists", "snapshot=Action_18.inf");
	truclient_step("19", "Click on Search Addresses, Parcels textbox", "snapshot=Action_19.inf");
	truclient_step("23", "Click on SliderBarPlusMouseOver", "snapshot=Action_23.inf");
	truclient_step("24", "Wait 2 seconds", "snapshot=Action_24.inf");
	truclient_step("25", "Evaluate JavaScript code Utils.addAutoHeader('App... Records', true)", "snapshot=Action_25.inf");
	lr_start_transaction("GIS_AA_Search Bar_Parcel Panel_Show Records");
	truclient_step("45", "Click on SliderBarPlusMouseOver", "snapshot=Action_45.inf");
	truclient_step("47", "Click on ShowPanListIcon", "snapshot=Action_47.inf");
	truclient_step("52", "Click on Select by rectangle listitem", "snapshot=Action_52.inf");
	truclient_step("56", "Wait until Search Addresses, Parcels textbox exists", "snapshot=Action_56.inf");
	lr_end_transaction("GIS_AA_Search Bar_Parcel Panel_Show Records",0);
	truclient_step("57", "Wait 2 seconds", "snapshot=Action_57.inf");
	truclient_step("61", "Click on SliderBarPlusMouseOver", "snapshot=Action_61.inf");
	truclient_step("123", "Click on Search Addresses, Parcels textbox", "snapshot=Action_123.inf");
	truclient_step("124", "Evaluate JavaScript code Utils.addAutoHeader('App...el Panel', true)", "snapshot=Action_124.inf");
	lr_start_transaction("GIS_AA_Search Bar_Parcel Panel");
	truclient_step("125", "Type 302731000000100000 in Search Addresses, Parcels textbox", "snapshot=Action_125.inf");
	truclient_step("126", "Press key Enter on Search Addresses, Parcels textbox", "snapshot=Action_126.inf");
	truclient_step("138", "Wait until Search Addresses, Parcels textbox exists", "snapshot=Action_138.inf");
	lr_end_transaction("GIS_AA_Search Bar_Parcel Panel",0);
	truclient_step("139", "Wait 2 seconds", "snapshot=Action_139.inf");
	truclient_step("140", "Click on element (26)", "snapshot=Action_140.inf");
	truclient_step("142", "Click on Select by rectangle listitem", "snapshot=Action_142.inf");
	truclient_step("146", "Wait 2 seconds", "snapshot=Action_146.inf");
	truclient_step("147", "Click on element (2)", "snapshot=Action_147.inf");
	truclient_step("149", "Click on element (76)", "snapshot=Action_149.inf");
	truclient_step("155", "Wait 2 seconds", "snapshot=Action_155.inf");
	truclient_step("156", "Click on Close", "snapshot=Action_156.inf");
	truclient_step("157", "Click on focusable (1)", "snapshot=Action_157.inf");
	truclient_step("158", "Click on Tasks", "snapshot=Action_158.inf");
	truclient_step("159", "Wait 2 seconds", "snapshot=Action_159.inf");
	truclient_step("160", "Click on Button", "snapshot=Action_160.inf");
	truclient_step("161", "Click on All Pages", "snapshot=Action_161.inf");
	truclient_step("165", "Wait 2 seconds", "snapshot=Action_165.inf");
	truclient_step("166", "Type parcel in Filter textbox", "snapshot=Action_166.inf");
	truclient_step("167", "Press key Enter on Filter textbox", "snapshot=Action_167.inf");
	truclient_step("168", "Evaluate JavaScript code Utils.addAutoHeader('App...w Record', true)", "snapshot=Action_168.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel_Create New record_Show Record");
	truclient_step("169", "Click on Parcels", "snapshot=Action_169.inf");
	truclient_step("170", "Mouse down on Parcel # textbox", "snapshot=Action_170.inf");
	truclient_step("171", "Mouse down on Parcel # textbox", "snapshot=Action_171.inf");
	truclient_step("172", "Click on Parcel # textbox", "snapshot=Action_172.inf");
	truclient_step("175", "Type 302731000000100000 in Parcel # textbox", "snapshot=Action_175.inf");
	truclient_step("176", "Click on Submit", "snapshot=Action_176.inf");
	truclient_step("177", "Wait until Address columnheader exists", "snapshot=Action_177.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel_Create New record_Show Record",0);
	truclient_step("178", "Wait 2 seconds", "snapshot=Action_178.inf");
	truclient_step("179", "Click on Select checkbox", "snapshot=Action_179.inf");
	truclient_step("180", "Click on GIS", "snapshot=Action_180.inf");
	truclient_step("185", "Wait until RECORDS exists", "snapshot=Action_185.inf");
	truclient_step("186", "Evaluate JavaScript code Utils.addAutoHeader('App...Document', true)", "snapshot=Action_186.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel_Records_Show Document");
	truclient_step("187", "Click on New label", "snapshot=Action_187.inf");
	truclient_step("188", "Click on Create Inspection", "snapshot=Action_188.inf");
	truclient_step("189", "Wait until Cancel JavaScript link exists", "snapshot=Action_189.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel_Records_Show Document",0);
	truclient_step("190", "Wait 2 seconds", "snapshot=Action_190.inf");
	truclient_step("191", "Activate browser window #2", "snapshot=Action_191.inf");
	truclient_step("192", "Activate tab 1", "snapshot=Action_192.inf");
	truclient_step("194", "Click on Cancel JavaScript link", "snapshot=Action_194.inf");
	truclient_step("195", "Activate browser window #1", "snapshot=Action_195.inf");
	truclient_step("196", "Evaluate JavaScript code Utils.addAutoHeader('App...w Record', true)", "snapshot=Action_196.inf");
	lr_start_transaction("GIS_AA_Search Bar_Parcel Panel_Create New Record");
	truclient_step("197", "Click on New label", "snapshot=Action_197.inf");
	truclient_step("199", "Click on Create New Record", "snapshot=Action_199.inf");
	truclient_step("200", "Wait until Search Record Type label exists", "snapshot=Action_200.inf");
	lr_end_transaction("GIS_AA_Search Bar_Parcel Panel_Create New Record",0);
	truclient_step("201", "Wait 2 seconds", "snapshot=Action_201.inf");
	truclient_step("202", "Activate browser window #2", "snapshot=Action_202.inf");
	truclient_step("203", "Activate tab 1", "snapshot=Action_203.inf");
	truclient_step("204", "Click on Cancel", "snapshot=Action_204.inf");
	truclient_step("205", "Activate browser window #1", "snapshot=Action_205.inf");
	truclient_step("207", "Evaluate JavaScript code Utils.addAutoHeader('App...Document', true)", "snapshot=Action_207.inf");
	lr_start_transaction("GIS_AA_Search Bar_Parcel Panel_Show Document");
	truclient_step("208", "Click on New label", "snapshot=Action_208.inf");
	truclient_step("210", "Click on Show Document", "snapshot=Action_210.inf");
	truclient_step("211", "Wait until Close JavaScript link exists", "snapshot=Action_211.inf");
	lr_end_transaction("GIS_AA_Search Bar_Parcel Panel_Show Document",0);
	truclient_step("212", "Wait 2 seconds", "snapshot=Action_212.inf");
	truclient_step("213", "Activate browser window #2", "snapshot=Action_213.inf");
	truclient_step("214", "Activate tab 1", "snapshot=Action_214.inf");
	truclient_step("216", "Click on Close JavaScript link", "snapshot=Action_216.inf");
	truclient_step("217", "Activate browser window #1", "snapshot=Action_217.inf");
	truclient_step("218", "Click on New label", "snapshot=Action_218.inf");
	truclient_step("220", "Wait 2 seconds", "snapshot=Action_220.inf");
	truclient_step("221", "Scroll on Create Inspection Create...", "snapshot=Action_221.inf");
	truclient_step("223", "Evaluate JavaScript code Utils.addAutoHeader('App...election', true)", "snapshot=Action_223.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel_Create New record_Buffer selection");
	truclient_step("224", "Click on Buffer Selection", "snapshot=Action_224.inf");
	truclient_step("226", "Mouse down on 500 textbox", "snapshot=Action_226.inf");
	truclient_step("228", "Mouse up on Map: Accela(SitusAddress...g)(Commercial...", "snapshot=Action_228.inf");
	truclient_step("229", "Type 1000 in 500 textbox", "snapshot=Action_229.inf");
	truclient_step("231", "Click on OK button", "snapshot=Action_231.inf");
	truclient_step("234", "Wait until PARCELS exists", "snapshot=Action_234.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel_Create New record_Buffer selection",0);
	truclient_step("235", "Wait 2 seconds", "snapshot=Action_235.inf");
	truclient_step("236", "Mouse down on element (2)", "snapshot=Action_236.inf");
	truclient_step("237", "Click on element (2)", "snapshot=Action_237.inf");
	truclient_step("240", "Evaluate JavaScript code Utils.addAutoHeader('App...w record', true)", "snapshot=Action_240.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel_Parcel_Create New record");
	truclient_step("241", "Click on focusable (1)", "snapshot=Action_241.inf");
	truclient_step("242", "Click on focusable (1)", "snapshot=Action_242.inf");
	truclient_step("243", "Click on Tasks", "snapshot=Action_243.inf");
	truclient_step("244", "Click on Button", "snapshot=Action_244.inf");
	truclient_step("247", "Type RECORD in Filter textbox", "snapshot=Action_247.inf");
	truclient_step("248", "Click on Record", "snapshot=Action_248.inf");
	truclient_step("249", "Click on Search link", "snapshot=Action_249.inf");
	truclient_step("250", "Wait until Record Type label exists", "snapshot=Action_250.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel_Parcel_Create New record",0);
	truclient_step("251", "Wait 2 seconds", "snapshot=Action_251.inf");
	truclient_step("252", "Click on To textbox", "snapshot=Action_252.inf");
	truclient_step("253", "Click on To textbox", "snapshot=Action_253.inf");
	truclient_step("254", "Evaluate JavaScript code Utils.addAutoHeader('App...r Select', true)", "snapshot=Action_254.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel_Buffer Select");
	truclient_step("255", "Type A18-008911 in To textbox", "snapshot=Action_255.inf");
	truclient_step("256", "Click on Submit", "snapshot=Action_256.inf");
	truclient_step("257", "Click on Select checkbox", "snapshot=Action_257.inf");
	truclient_step("258", "Click on GIS", "snapshot=Action_258.inf");
	truclient_step("260", "Wait until Search Addresses, Parcels textbox exists", "snapshot=Action_260.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel_Buffer Select",0);
	truclient_step("261", "Wait 2 seconds", "snapshot=Action_261.inf");
	truclient_step("262", "Evaluate JavaScript code Utils.addAutoHeader('App...w record', true)", "snapshot=Action_262.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel_Create New record");
	truclient_step("263", "Click on element (4)", "snapshot=Action_263.inf");
	truclient_step("264", "Click on Create Inspection", "snapshot=Action_264.inf");
	truclient_step("265", "Wait until Cancel JavaScript link exists", "snapshot=Action_265.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel_Create New record",0);
	truclient_step("266", "Wait 2 seconds", "snapshot=Action_266.inf");
	truclient_step("267", "Activate browser window #2", "snapshot=Action_267.inf");
	truclient_step("268", "Activate tab 1", "snapshot=Action_268.inf");
	truclient_step("269", "Click on Cancel JavaScript link", "snapshot=Action_269.inf");
	truclient_step("270", "Activate browser window #1", "snapshot=Action_270.inf");
	truclient_step("271", "Mouse Over", "snapshot=Action_271.inf");
	{
		truclient_step("271.2", "Move mouse over Create InspectionShow...", "snapshot=Action_271.2.inf");
	}
	truclient_step("272", "Evaluate JavaScript code Utils.addAutoHeader('App...document', true)", "snapshot=Action_272.inf");
	truclient_step("273", "Click on element (4)", "snapshot=Action_273.inf");
	truclient_step("274", "Click on Show Document", "snapshot=Action_274.inf");
	truclient_step("275", "Wait until Document Name exists", "snapshot=Action_275.inf");
	truclient_step("276", "Wait 2 seconds", "snapshot=Action_276.inf");
	truclient_step("277", "Activate browser window #2", "snapshot=Action_277.inf");
	truclient_step("278", "Activate tab 1", "snapshot=Action_278.inf");
	truclient_step("280", "Click on Close JavaScript link", "snapshot=Action_280.inf");
	truclient_step("281", "Activate browser window #1", "snapshot=Action_281.inf");
	truclient_step("282", "Click on element (4)", "snapshot=Action_282.inf");
	truclient_step("283", "Scroll on Create Inspection Show...", "snapshot=Action_283.inf");
	truclient_step("285", "Click on element (6)", "snapshot=Action_285.inf");
	truclient_step("287", "Wait 2 seconds", "snapshot=Action_287.inf");
	truclient_step("288", "Click on element (7)", "snapshot=Action_288.inf");
	truclient_step("289", "Click on element (8)", "snapshot=Action_289.inf");
	truclient_step("291", "Wait 2 seconds", "snapshot=Action_291.inf");
	truclient_step("292", "Click on Back to", "snapshot=Action_292.inf");
	truclient_step("293", "Evaluate JavaScript code Utils.addAutoHeader('App...ss Panel', true)", "snapshot=Action_293.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel");
	truclient_step("294", "Click on A18 008911 link", "snapshot=Action_294.inf");
	truclient_step("295", "Click on Address link", "snapshot=Action_295.inf");
	truclient_step("296", "Wait until Address Locator exists", "snapshot=Action_296.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel",0);
	truclient_step("297", "Wait 2 seconds", "snapshot=Action_297.inf");
	truclient_step("298", "Evaluate JavaScript code Utils.addAutoHeader('App...ormation', true)", "snapshot=Action_298.inf");
	lr_start_transaction("GIS_AA_Search Bar_Address Panel_Show GIS Information");
	truclient_step("299", "Click on Select checkbox", "snapshot=Action_299.inf");
	truclient_step("300", "Click on Address Locator", "snapshot=Action_300.inf");
	truclient_step("301", "Click on GIS", "snapshot=Action_301.inf");
	truclient_step("302", "Wait until GIS exists", "snapshot=Action_302.inf");
	lr_end_transaction("GIS_AA_Search Bar_Address Panel_Show GIS Information",0);
	truclient_step("303", "Wait 2 seconds", "snapshot=Action_303.inf");
	truclient_step("304", "Click on Cancel link", "snapshot=Action_304.inf");
	truclient_step("305", "Evaluate JavaScript code Utils.addAutoHeader('App...Sign Out', true)", "snapshot=Action_305.inf");
	lr_start_transaction("GIS_AA_Sign Out");
	truclient_step("306", "Click on element (1)", "snapshot=Action_306.inf");
	truclient_step("307", "Click on Sign Out link", "snapshot=Action_307.inf");
	lr_end_transaction("GIS_AA_Sign Out",0);

	return 0;
}
