Action()
{

	web_set_sockets_option("SSL_VERSION", "2&3");

	web_url("dashboard.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=", 
		"Snapshot=t1.inf", 
		"Mode=HTML", 
		LAST);

/*Correlation comment: Automatic rules - Do not change!  
Original value='517451ce5' 
Name ='requestToken' 
Type ='Rule' 
AppName ='AA' 
RuleName ='AutoGeneratedRuleName'*/
	web_reg_save_param_regexp(
		"ParamName=requestToken",
		"RegExp=name=\"requestToken\"\\ value=\"(.*?)\">\\\r\\\n\\\t\\\t<input\\ type",
		"Ordinal=1",
		SEARCH_FILTERS,
		"Scope=Body",
		"RequestUrl=*/hostSignon.do*",
		LAST);

/*Correlation comment: Automatic rules - Do not change!  
Original value='63227393ef' 
Name ='requestLanguageToken' 
Type ='Rule' 
AppName ='AA' 
RuleName ='AutoGeneratedRuleName_1'*/
	web_reg_save_param_regexp(
		"ParamName=requestLanguageToken",
		"RegExp=name=\"requestLanguageToken\"\\ value=\"(.*?)\"\\ id",
		"Ordinal=1",
		SEARCH_FILTERS,
		"Scope=Body",
		"RequestUrl=*/hostSignon.do*",
		LAST);

	web_url("hostSignon.do", 
		"URL=https://av-pt-ferrari.accela.com/security/hostSignon.do?successUrl=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/ssoAdapter/loginAction.do?successURL=https%3A%2F%2Fav-pt-ferrari.accela.com%2Fportlets%2Fspa%2Fdashboard.do&SignOnModule=", 
		"Snapshot=t2.inf", 
		"Mode=HTML", 
		LAST);

	lr_think_time(23);

	web_url("plugins_win.json", 
		"URL=https://www.gstatic.com/chrome/config/plugins_2/plugins_win.json", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=", 
		"Snapshot=t3.inf", 
		"Mode=HTML", 
		LAST);

	lr_think_time(49);
    web_add_header("AppD_Header", "MILARA_Login");
	lr_start_transaction("MILARA_Login");

	web_custom_request("loginAction.do", 
		"URL=https://av-pt-ferrari.accela.com/ssoAdapter/loginAction.do?requestType=checkWebSSOAdapter&servProvCode=MILARA", 
		"Method=GET", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/security/hostSignon.do?hostSignOn=true", 
		"Snapshot=t4.inf", 
		"Mode=HTML", 
		"EncType=application/x-www-form-urlencoded", 
		LAST);

	lr_think_time(6);

	web_submit_data("hostSignon.do_2",
		"Action=https://av-pt-ferrari.accela.com/security/hostSignon.do?hostSignOn=true",
		"Method=POST",
		"TargetFrame=",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/security/hostSignon.do?hostSignOn=true",
		"Snapshot=t5.inf",
		"Mode=HTML",
		ITEMDATA,
		"Name=action", "Value=signon", ENDITEM,
		"Name=successUrl", "Value=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", ENDITEM,
		"Name=cookieUserName", "Value=", ENDITEM,
		"Name=cookieAgencyName", "Value=", ENDITEM,
		"Name=requestToken", "Value={requestToken}", ENDITEM,
		"Name=requestLanguageToken", "Value={requestLanguageToken}", ENDITEM,
		"Name=password1", "Value=", ENDITEM,
		"Name=servProvCode", "Value=MILARA", ENDITEM,
		"Name=username", "Value=admin", ENDITEM,
		"Name=password", "Value=admin", ENDITEM,
		"Name=accela_select_language", "Value=en_US", ENDITEM,
		"Name=submit_", "Value=Login", ENDITEM,
		LAST);

	web_url("dashboard.do_2", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/security/hostSignon.do?hostSignOn=true", 
		"Snapshot=t7.inf", 
		"Mode=HTML", 
		LAST);

	web_custom_request("text.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/text.do?mode=localizedText", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t8.inf", 
		"Mode=HTML", 
		"EncType=application/json;charset=UTF-8", 
		"Body={\"AANewUX_ApplicationMenu_Administration\":\"\",\"AANewUX_ApplicationMenu_CivicPlatform\":\"\",\"AANewUX_ApplicationMenu_ExitAdministration\":\"\",\"AANewUX_ApplicationMenu_ClassicAdministration\":\"\",\"AANewUX_ApplicationMenu_ExitClassicAdministration\":\"\",\"AANewUX_ApplicationMenu_Help\":\"\",\"AANewUX_ApplicationMenu_SignOut\":\"\",\"AANewUX_ApplicationMenu_SwitchToV360\":\"\",\"AANewUX_Dialog_Close\":\"\",\"AANewUX_Dialog_PortletErrorTitle\":\"\",\"AANewUX_Dialog_URLRequired\":\"\",\""
		"AANewUX_Error_InvalidResponse\":\"\",\"AANewUX_Error_SessionTimedOut\":\"\",\"AANewUX_GIS_CreateInspections\":\"\",\"AANewUX_GIS_Actions\":\"\",\"AANewUX_GIS_AccelaRecords\":\"\",\"AANewUX_GIS_Address\":\"\",\"AANewUX_GIS_Addresses\":\"\",\"AANewUX_GIS_Assets\":\"\",\"AANewUX_GIS_Contents\":\"\",\"AANewUX_GIS_NotPlotted\":\"\",\"AANewUX_GIS_AllRecords\":\"\",\"AANewUX_GIS_AllTransactions\":\"\",\"AANewUX_GIS_AssetGroup\":\"\",\"AANewUX_GIS_AssetID\":\"\",\"AANewUX_GIS_AssetType\":\"\",\""
		"AANewUX_GIS_ClassType\":\"\",\"AANewUX_GIS_ClearAll\":\"\",\"AANewUX_GIS_AttachToRecord\":\"\",\"AANewUX_GIS_BufferSelection\":\"\",\"AANewUX_GIS_DriveTimeBufferSelection\":\"\",\"AANewUX_GIS_CreateNewRecord\":\"\",\"AANewUX_GIS_CreateWorkOrder\":\"\",\"AANewUX_GIS_CreateMultipleWorkOrders\":\"\",\"AANewUX_GIS_ExportToCSV\":\"\",\"AANewUX_GIS_Description\":\"\",\"AANewUX_GIS_GISObjects\":\"\",\"AANewUX_GIS_HideDetails\":\"\",\"AANewUX_GIS_InstallDate\":\"\",\"AANewUX_GIS_Inspections\":\"\",\""
		"AANewUX_GIS_InspectionType\":\"\",\"AANewUX_GIS_OpenedDate\":\"\",\"AANewUX_GIS_Owner\":\"\",\"AANewUX_GIS_Parcel\":\"\",\"AANewUX_GIS_Parcels\":\"\",\"AANewUX_GIS_Permits\":\"\",\"AANewUX_GIS_ParcelID\":\"\",\"AANewUX_GIS_RecordID\":\"\",\"AANewUX_GIS_PermitID\":\"\",\"AANewUX_GIS_Records\":\"\",\"AANewUX_GIS_RecordType\":\"\",\"AANewUX_GIS_ScheduledDate\":\"\",\"AANewUX_GIS_SelectNearbyFeatures\":\"\",\"AANewUX_GIS_SendGISFeature\":\"\",\"AANewUX_GIS_ShowDetails\":\"\",\""
		"AANewUX_GIS_ShowDocument\":\"\",\"AANewUX_GIS_ShowingResults\":\"\",\"AANewUX_GIS_Status\":\"\",\"AANewUX_GIS_TooManyGisObjectsTitle\":\"\",\"AANewUX_GIS_TooManyGisObjectsMsg\":\"\",\"AANewUX_GIS_Transactions\":\"\",\"AANewUX_GIS_XCoordinate\":\"\",\"AANewUX_GIS_YCoordinate\":\"\",\"AANewUX_GIS_ZipCode\":\"\",\"AANewUX_GIS_InspRecords\":\"\",\"AANewUX_GIS_selected\":\"\",\"AANewUX_GIS_SelectAll\":\"\",\"AANewUX_GIS_DeselectAll\":\"\",\"AANewUX_GIS_Opened\":\"\",\"AANewUX_GIS_MORE\":\"\",\""
		"AANewUX_GIS_NewPanelRecords\":\"\",\"AANewUX_GlobalSearch_Address\":\"\",\"AANewUX_GlobalSearch_Agency\":\"\",\"AANewUX_GlobalSearch_AltID\":\"\",\"AANewUX_GlobalSearch_Applicant\":\"\",\"AANewUX_GlobalSearch_ApplicationName\":\"\",\"AANewUX_GlobalSearch_AssetInfo\":\"\",\"AANewUX_GlobalSearch_AssetsTab\":\"\",\"AANewUX_GlobalSearch_BusinessName\":\"\",\"AANewUX_GlobalSearch_ColumnView\":\"\",\"AANewUX_GlobalSearch_Contact\":\"\",\"AANewUX_GlobalSearch_ContactNumber\":\"\",\""
		"AANewUX_GlobalSearch_ContactBusinessName\":\"\",\"AANewUX_GlobalSearch_ContactsTab\":\"\",\"AANewUX_GlobalSearch_ContactType\":\"\",\"AANewUX_GlobalSearch_CreatedDate\":\"\",\"AANewUX_GlobalSearch_CreatedOn\":\"\",\"AANewUX_GlobalSearch_Description\":\"\",\"AANewUX_GlobalSearch_Document\":\"\",\"AANewUX_GlobalSearch_DocumentCategory\":\"\",\"AANewUX_GlobalSearch_DocumentName\":\"\",\"AANewUX_GlobalSearch_DocumentStatus\":\"\",\"AANewUX_GlobalSearch_DocumentsTab\":\"\",\"AANewUX_GlobalSearch_Email"
		"\":\"\",\"AANewUX_GlobalSearch_FilterButton\":\"\",\"AANewUX_GlobalSearch_FullName\":\"\",\"AANewUX_GlobalSearch_LastPage\":\"\",\"AANewUX_GlobalSearch_LastUpdatedOn\":\"\",\"AANewUX_GlobalSearch_LicenseExpiresOn\":\"\",\"AANewUX_GlobalSearch_LicenseIssuedOn\":\"\",\"AANewUX_GlobalSearch_LicenceProfessionalsTab\":\"\",\"AANewUX_GlobalSearch_LicenseType\":\"\",\"AANewUX_GlobalSearch_Location\":\"\",\"AANewUX_GlobalSearch_LocationsTab\":\"\",\"AANewUX_GlobalSearch_NextPageLink\":\"\",\""
		"AANewUX_GlobalSearch_Owner\":\"\",\"AANewUX_GlobalSearch_Page\":\"\",\"AANewUX_GlobalSearch_Parcel\":\"\",\"AANewUX_GlobalSearch_ParcelsTab\":\"\",\"AANewUX_GlobalSearch_PhoneNumber\":\"\",\"AANewUX_GlobalSearch_ProjectName\":\"\",\"AANewUX_GlobalSearch_Record\":\"\",\"AANewUX_GlobalSearch_RecordID\":\"\",\"AANewUX_GlobalSearch_RecordInfo\":\"\",\"AANewUX_GlobalSearch_RecordsTab\":\"\",\"AANewUX_GlobalSearch_RecordType\":\"\",\"AANewUX_GlobalSearch_ReportedType\":\"\",\""
		"AANewUX_GlobalSearch_ResultsCount\":\"\",\"AANewUX_GlobalSearch_Review\":\"\",\"AANewUX_GlobalSearch_PreviousPageLink\":\"\",\"AANewUX_GlobalSearch_ShortNotes\":\"\",\"AANewUX_GlobalSearch_Showing\":\"\",\"AANewUX_GlobalSearch_SortByMostRecent\":\"\",\"AANewUX_GlobalSearch_Status\":\"\",\"AANewUX_GlobalSearch_StatusDate\":\"\",\"AANewUX_GlobalSearch_StateLicenseNo\":\"\",\"AANewUX_GlobalSearch_TabRecordCount\":\"\",\"AANewUX_GlobalSearch_TradeName\":\"\",\"AANewUX_GlobalSearch_Type\":\"\",\""
		"AANewUX_GlobalSearchForm_Advanced\":\"\",\"AANewUX_GlobalSearchForm_RecentSearches\":\"\",\"AANewUX_GlobalSearchForm_InputPlaceholder\":\"\",\"AANewUX_GlobalSearchForm_SubmitButtonText\":\"\",\"AANewUX_Launchpad_Address\":\"\",\"AANewUX_Launchpad_AddFavorite\":\"\",\"AANewUX_Launchpad_AllPages\":\"\",\"AANewUX_Launchpad_Assets\":\"\",\"AANewUX_Launchpad_ClearAll\":\"\",\"AANewUX_Launchpad_Contacts\":\"\",\"AANewUX_Launchpad_Filter\":\"\",\"AANewUX_Launchpad_FilterList\":\"\",\""
		"AANewUX_Launchpad_HideAllPages\":\"\",\"AANewUX_Launchpad_New\":\"\",\"AANewUX_Launchpad_NewApplication\":\"\",\"AANewUX_Launchpad_Owners\":\"\",\"AANewUX_Launchpad_Parcels\":\"\",\"AANewUX_Launchpad_Professionals\":\"\",\"AANewUX_Launchpad_Recent\":\"\",\"AANewUX_Launchpad_ShowAllPages\":\"\",\"AANewUX_Launchpad_YourPages\":\"\",\"AANewUX_Launchpad_RemoveFavorite\":\"\",\"AANewUX_MainMenu_Label\":\"\",\"AANewUX_MainMenu_DashboardActive\":\"\",\"AANewUX_MainMenu_DashboardOpen\":\"\",\""
		"AANewUX_MainMenu_GlobalSearchOpen\":\"\",\"AANewUX_MainMenu_GlobalSearchClose\":\"\",\"AANewUX_MainMenu_LaunchpadOpen\":\"\",\"AANewUX_MainMenu_LaunchpadClose\":\"\",\"AANewUX_Task_Actions\":\"\",\"AANewUX_Task_Active\":\"\",\"AANewUX_Task_ActivityDeleteSuccess\":\"\",\"AANewUX_Task_ActivityID\":\"\",\"AANewUX_Task_Address\":\"\",\"AANewUX_Task_Agenda\":\"\",\"AANewUX_Task_AllPages\":\"\",\"AANewUX_Task_AltID\":\"\",\"AANewUX_Task_AlternateID\":\"\",\"AANewUX_Task_Assign\":\"\",\""
		"AANewUX_Task_Assigned\":\"\",\"AANewUX_Task_AssignedTo\":\"\",\"AANewUX_Task_Cancel\":\"\",\"AANewUX_Task_Category\":\"\",\"AANewUX_Task_CategoryACTIVITY\":\"\",\"AANewUX_Task_CategoryDOCUMENT\":\"\",\"AANewUX_Task_CategoryINSPECTION\":\"\",\"AANewUX_Task_CategoryMEETING\":\"\",\"AANewUX_Task_CategoryWORKFLOW\":\"\",\"AANewUX_Task_Claim\":\"\",\"AANewUX_Task_Clear\":\"\",\"AANewUX_Task_ColumnView\":\"\",\"AANewUX_Task_Completed\":\"\",\"AANewUX_Task_ConditionApplied\":\"\",\""
		"AANewUX_Task_ConditionPlusNMore\":\"\",\"AANewUX_Task_Delete\":\"\",\"AANewUX_Task_DocumentActionNotDefined\":\"\",\"AANewUX_Task_DocumentPreviewPermissionFail\":\"\",\"AANewUX_Task_Download\":\"\",\"AANewUX_Task_Due\":\"\",\"AANewUX_Task_DueInNDays\":\"\",\"AANewUX_Task_DueDateNotAssigned\":\"\",\"AANewUX_Task_DueToday\":\"\",\"AANewUX_Task_Duplicate\":\"\",\"AANewUX_Task_Duration\":\"\",\"AANewUX_Task_DurationHour\":\"\",\"AANewUX_Task_DurationHours\":\"\",\"AANewUX_Task_DurationMinute\":\"\",\""
		"AANewUX_Task_DurationMinutes\":\"\",\"AANewUX_Task_ExportToCSV\":\"\",\"AANewUX_Task_Filter\":\"\",\"AANewUX_Task_FilterAdvanced\":\"\",\"AANewUX_Task_FilterApply\":\"\",\"AANewUX_Task_FilterClearAll\":\"\",\"AANewUX_Task_FilterDateRangeAssigned\":\"\",\"AANewUX_Task_FilterDateRangeDue\":\"\",\"AANewUX_Task_FilterDateRangeOpen\":\"\",\"AANewUX_Task_FilterDateRangeStatus\":\"\",\"AANewUX_Task_FilterFrom\":\"\",\"AANewUX_Task_FilterSelected\":\"\",\"AANewUX_Task_FilterSave\":\"\",\""
		"AANewUX_Task_FilterStatusCompleted\":\"\",\"AANewUX_Task_FilterTabAssignedTo\":\"\",\"AANewUX_Task_FilterTabDateRange\":\"\",\"AANewUX_Task_FilterTabSaved\":\"\",\"AANewUX_Task_FilterTabStatus\":\"\",\"AANewUX_Task_FilterTabType\":\"\",\"AANewUX_Task_FilterTo\":\"\",\"AANewUX_Task_Group\":\"\",\"AANewUX_Task_HasNoAddress\":\"\",\"AANewUX_Task_HasNoCity\":\"\",\"AANewUX_Task_HasNoComment\":\"\",\"AANewUX_Task_HasNoDescription\":\"\",\"AANewUX_Task_HasNoLocation\":\"\",\""
		"AANewUX_Task_HasNoMeetingBody\":\"\",\"AANewUX_Task_HasNoScheduledTime\":\"\",\"AANewUX_Task_InspectionCancelSuccess\":\"\",\"AANewUX_Task_InspectionDeleteFail\":\"\",\"AANewUX_Task_InspectionDeleteSuccess\":\"\",\"AANewUX_Task_InTheAfternoon\":\"\",\"AANewUX_Task_InTheMorning\":\"\",\"AANewUX_Task_Location\":\"\",\"AANewUX_Task_LoadMore\":\"\",\"AANewUX_Task_LoadingTasks\":\"\",\"AANewUX_Task_MeetingRejectedSuccess\":\"\",\"AANewUX_Task_NoMoreRecordsAvailable\":\"\",\""
		"AANewUX_Task_NoTasksAssigned\":\"\",\"AANewUX_Task_NoTasksFound\":\"\",\"AANewUX_Task_NoFilteredTasksFound\":\"\",\"AANewUX_Task_NoQuickQueriesFound\":\"\",\"AANewUX_Task_PageLabel\":\"\",\"AANewUX_Task_PageOfLabel\":\"\",\"AANewUX_Task_Preview\":\"\",\"AANewUX_Task_PreviewDocument\":\"\",\"AANewUX_Task_Print\":\"\",\"AANewUX_Task_QuickQueries\":\"\",\"AANewUX_Task_Reassign\":\"\",\"AANewUX_Task_RecordAgendaSetSuccess\":\"\",\"AANewUX_Task_RecordActionDownloadSuccess\":\"\",\""
		"AANewUX_Task_RecordDuplicateSuccess\":\"\",\"AANewUX_Task_RecordID\":\"\",\"AANewUX_Task_RecordReassignSuccess\":\"\",\"AANewUX_Task_RecordRemoveSuccess\":\"\",\"AANewUX_Task_RecordRescheduleSuccess\":\"\",\"AANewUX_Task_RecordReviewSuccess\":\"\",\"AANewUX_Task_RecordType\":\"\",\"AANewUX_Task_Reject\":\"\",\"AANewUX_Task_Release\":\"\",\"AANewUX_Task_Remove\":\"\",\"AANewUX_Task_Reschedule\":\"\",\"AANewUX_Task_Result\":\"\",\"AANewUX_Task_Review\":\"\",\"AANewUX_Task_Schedule\":\"\",\""
		"AANewUX_Task_ShowingNTasks\":\"\",\"AANewUX_Task_ShowingNFilteredTasks\":\"\",\"AANewUX_Task_Sort\":\"\",\"AANewUX_Task_Success\":\"\",\"AANewUX_Task_TaskErrorHeading\":\"\",\"AANewUX_Task_TaskName\":\"\",\"AANewUX_Task_TaskListFixedColumnHeader\":\"\",\"AANewUX_Task_TaskListDueDateHeader\":\"\",\"AANewUX_Task_TaskListFlagsHeader\":\"\",\"AANewUX_Task_TaskListStatusHeader\":\"\",\"AANewUX_Task_TaskListDetailsHeader\":\"\",\"AANewUX_Task_Tasks\":\"\",\"AANewUX_Task_TotalTasks\":\"\",\""
		"AANewUX_Task_Type\":\"\",\"AANewUX_Task_ViewDocInfo\":\"\",\"AANewUX_Task_Warning\":\"\",\"AANewUX_Task_Workflow\":\"\",\"AANewUX_Task_WorkflowClaimFail\":\"\",\"AANewUX_Task_WorkflowClaimPermissionFail\":\"\",\"AANewUX_Task_WorkflowClaimSuccess\":\"\",\"AANewUX_Task_WorkflowReleaseFail\":\"\",\"AANewUX_Task_WorkflowReleasePermissionFail\":\"\",\"AANewUX_Task_WorkflowReleaseSuccess\":\"\",\"AANewUX_Tooltip_CardView\":\"\",\"AANewUX_Tooltip_ListView\":\"\",\"AANewUX_Tooltip_Map\":\"\",\""
		"AANewUX_Tooltip_SuperAgencyDashboard\":\"\",\"AANewUX_Tooltip_Tasks\":\"\",\"AANewUX_Workspace_Close\":\"\",\"AANewUX_Workspace_More\":\"\",\"AANewUX_Workspace_OpenSpaces\":\"\",\"AANewUX_Workspace_Pin\":\"\",\"AANewUX_Workspace_Unpin\":\"\"}", 
		LAST);

	web_custom_request("userinfo.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/user/userinfo.do?mode=userInfo", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/x-json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t9.inf", 
		"Mode=HTML", 
		"EncType=application/json;charset=UTF-8", 
		"Body={}", 
		LAST);

	web_url("session.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.mytask-list", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t10.inf", 
		"Mode=HTML", 
		LAST);

	lr_end_transaction("MILARA_Login",LR_AUTO);

	lr_think_time(17);
    web_add_header("AppD_Header", "MILARA_TC1_01_Click_Records");
	lr_start_transaction("MILARA_TC1_01_Click_Records");

	web_url("session.do_2", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=null", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t11.inf", 
		"Mode=HTML", 
		LAST);

	web_url("session.do_3", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.mytask-list", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t12.inf", 
		"Mode=HTML", 
		LAST);

	web_url("session.do_4", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=null", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t13.inf", 
		"Mode=HTML", 
		LAST);

	web_url("session.do_5", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t14.inf", 
		"Mode=HTML", 
		LAST);

	web_url("myCAPDetailPortlet.jsp", 
		"URL=https://av-pt-ferrari.accela.com/portlets/commons/cap/myCAPDetailPortlet.jsp?module=-select-", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t15.inf", 
		"Mode=HTML", 
		LAST);

	web_url("View the content of this inline frame", 
		"URL=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/blank.jsp", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?searchBy=ByCondition&height=270&mode=init&module=Licenses&cleanCapId=Y&isGeneralCAP=Y&supportMulAgencySearch=Y", 
		"Snapshot=t16.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("empty.jsp", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t17.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	lr_end_transaction("MILARA_TC1_01_Click_Records",LR_AUTO);
    web_add_header("AppD_Header", "MILARA_TC1_02_Click_Search");
	lr_start_transaction("MILARA_TC1_02_Click_Search");

	web_url("session.do_6", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?searchBy=ByCondition&height=270&mode=init&module=Licenses&cleanCapId=Y&isGeneralCAP=Y&supportMulAgencySearch=Y", 
		"Snapshot=t18.inf", 
		"Mode=HTML", 
		LAST);

	web_url("capSearch.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?searchBy=ByCondition&height=270&mode=init&module=Licenses&cleanCapId=Y&isGeneralCAP=Y&supportMulAgencySearch=Y", 
		"Snapshot=t19.inf", 
		"Mode=HTML", 
		LAST);

	web_url("blank.jsp", 
		"URL=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/blank.jsp", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", 
		"Snapshot=t20.inf", 
		"Mode=HTML", 
		LAST);

	web_url("formAjaxUtil.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/formAjaxUtil.do?portlet_language=en_US&attriKey=capSearchForm&staffName=value(capDetailModel*asgnStaff)&userType=1&dept=&mode=getStaffsByDept", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", 
		"Snapshot=t21.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("empty.jsp_2", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t22.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_submit_data("regionalSyncMask.do", 
		"Action=https://av-pt-ferrari.accela.com/portlets/regional/regionalSyncMask.do?mode=syncMask&maskType=postalCode&referValue=", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", 
		"Snapshot=t23.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_submit_data("regionalSyncMask.do_2", 
		"Action=https://av-pt-ferrari.accela.com/portlets/regional/regionalSyncMask.do?mode=syncMask&maskType=postalCode&getMsg=Y", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", 
		"Snapshot=t24.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	lr_end_transaction("MILARA_TC1_02_Click_Search",LR_AUTO);
    web_add_header("AppD_Header", "MILARA_TC1_03_Search_Record");
	lr_start_transaction("MILARA_TC1_03_Search_Record");

	web_url("session.do_7", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", 
		"Snapshot=t25.inf", 
		"Mode=HTML", 
		LAST);

/*Correlation comment: Automatic rules - Do not change!  
Original value='00VL9' 
Name ='Param_ID3' 
Type ='Rule' 
AppName ='AA' 
RuleName ='ID3'*/
	web_reg_save_param_ex(
		"ParamName=Param_ID3",
		"LB/IC=ID3=",
		"RB/IC=&requireNotice",
		SEARCH_FILTERS,
		"Scope=Body",
		"RequestUrl=*/capSearch.do*",
		LAST);

	web_submit_data("capSearch.do_2", 
		"Action=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?module=Licenses", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", 
		"Snapshot=t26.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		"Name=TRANSACTION_TOKEN_KEY_FOR_CAPSEARCHFORM", "Value=5f3cfd0928ee94b711639f3ae302be9a", ENDITEM, 
		"Name=value(FirstEntryURL)", "Value=/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", ENDITEM, 
		"Name=value(CurrentEntryURL)", "Value=/portlets/cap/capSearch.do?mode=search&isFromSearch=true&isSearchButton=true&module=Licenses&isGeneralCAP=Y", ENDITEM, 
		"Name=portlet_language", "Value=en_US", ENDITEM, 
		"Name=refresh_target", "Value=", ENDITEM, 
		"Name=refresh_url", "Value=", ENDITEM, 
		"Name=buttonName", "Value=", ENDITEM, 
		"Name=modeName", "Value=search", ENDITEM, 
		"Name=module", "Value=Licenses", ENDITEM, 
		"Name=accelasubmitbuttonname", "Value=submit", ENDITEM, 
		"Name=itemName", "Value=", ENDITEM, 
		"Name=CurrentViewID", "Value=115", ENDITEM, 
		"Name=exceptionLogID", "Value=", ENDITEM, 
		"Name=generalCAPSearch", "Value=", ENDITEM, 
		"Name=value(portlet_soundex)", "Value=off", ENDITEM, 
		"Name=isGeneralCAP", "Value=Y", ENDITEM, 
		"Name=objectName", "Value=", ENDITEM, 
		"Name=CheckBoxName", "Value=", ENDITEM, 
		"Name=MaxNumber", "Value=", ENDITEM, 
		"Name=ExportFileType", "Value=print", ENDITEM, 
		"Name=CurrentViewID", "Value=115", ENDITEM, 
		"Name=sessionIdFromWindow", "Value=lhOsuUEfqJyiZwzad17LYo1S", ENDITEM, 
		"Name=listID", "Value=", ENDITEM, 
		"Name=printType", "Value=", ENDITEM, 
		"Name=checkBoxValue", "Value=", ENDITEM, 
		"Name=action", "Value=", ENDITEM, 
		"Name=mode", "Value=submit", ENDITEM, 
		"Name=isSearchedFlag", "Value=Y", ENDITEM, 
		"Name=value(clear)", "Value=", ENDITEM, 
		"Name=value(isFromAdmin)", "Value=", ENDITEM, 
		"Name=formSearchPage", "Value=Y", ENDITEM, 
		"Name=value(supportMulAgencySearch)", "Value=Y", ENDITEM, 
		"Name=selectAgencies", "Value=", ENDITEM, 
		"Name=selectModules", "Value=", ENDITEM, 
		"Name=value(capModel*altID)", "Value=4704342632", ENDITEM, 
		"Name=value(capContactModel*userID)", "Value=", ENDITEM, 
		"Name=value(capContactModel*internalUserFlag)", "Value=", ENDITEM, 
		"Name=value(setDetailsModel*setMemberStatus)", "Value=", ENDITEM, 
		"Name=value(setDetailsModel*setMemberStatusDate)", "Value=", ENDITEM, 
		"Name=value(srLevel)", "Value=", ENDITEM, 
		"Name=value(capGroupIndex)", "Value=", ENDITEM, 
		"Name=value(capTypeModel*group)", "Value=", ENDITEM, 
		"Name=value(capTypeModel*type)", "Value=", ENDITEM, 
		"Name=value(capTypeModel*subType)", "Value=", ENDITEM, 
		"Name=value(capTypeModel*category)", "Value=", ENDITEM, 
		"Name=value(capTypeModel)", "Value=null/null/null/null", ENDITEM, 
		"Name=value(capModel*capStatus)", "Value=", ENDITEM, 
		"Name=value(capDetailModel*asgnDept)", "Value=", ENDITEM, 
		"Name=value(capDetailModel*asgnDept)", "Value=", ENDITEM, 
		"Name=value(capDetailModel*asgnStaff)", "Value=", ENDITEM, 
		"Name=date(capModel*fileDate)", "Value=08/28/2016", ENDITEM, 
		"Name=date(capModel*endFileDate)", "Value=08/28/2018", ENDITEM, 
		"Name=date(capDetailModel*firstIssuedDate)", "Value=", ENDITEM, 
		"Name=date(capDetailModel*endFirstIssuedDate)", "Value=", ENDITEM, 
		"Name=value(search_range_b1ExpirationModel*expDate)", "Value=", ENDITEM, 
		"Name=date(search_range_from_b1ExpirationModel*expDate)", "Value=", ENDITEM, 
		"Name=date(search_range_to_b1ExpirationModel*expDate)", "Value=", ENDITEM, 
		"Name=value(b1ExpirationModel*expStatus)", "Value=", ENDITEM, 
		"Name=value(historyTaskItemModel*taskDescription)", "Value=", ENDITEM, 
		"Name=value(licenseProfessionalModel*licensetype)", "Value=", ENDITEM, 
		"Name=value(licenseProfessionalModel*licensenbr)", "Value=", ENDITEM, 
		"Name=value(licenseProfessionalModel*contactFirstName)", "Value=", ENDITEM, 
		"Name=value(licenseProfessionalModel*contactLastName)", "Value=", ENDITEM, 
		"Name=date(licenseProfessionalModel*birthDate)", "Value=", ENDITEM, 
		"Name=date(licenseProfessionalModel*endBirthDate)", "Value=", ENDITEM, 
		"Name=value(licenseProfessionalModel*businessName)", "Value=", ENDITEM, 
		"Name=value(capContactModel*contactType)", "Value=", ENDITEM, 
		"Name=value(capContactModel*firstName)", "Value=", ENDITEM, 
		"Name=value(capContactModel*lastName)", "Value=", ENDITEM, 
		"Name=date(capContactModel*birthDate)", "Value=", ENDITEM, 
		"Name=date(capContactModel*endBirthDate)", "Value=", ENDITEM, 
		"Name=value(capContactModel*businessName)", "Value=", ENDITEM, 
		"Name=value(capContactModel*email)", "Value=", ENDITEM, 
		"Name=value(capContactModel*addressLine1)", "Value=", ENDITEM, 
		"Name=value(capContactModel*countryCode)", "Value=", ENDITEM, 
		"Name=value(capContactModel*city)", "Value=", ENDITEM, 
		"Name=value(capContactModel*state)", "Value=", ENDITEM, 
		"Name=value(capContactModel*zip_disp)", "Value=", ENDITEM, 
		"Name=value(capContactModel*zip)", "Value=", ENDITEM, 
		"Name=value(taskItemModel*taskDescription)", "Value=", ENDITEM, 
		"Name=value(taskItemModel*disposition)", "Value=", ENDITEM, 
		LAST);

	web_submit_data("empty.jsp_3", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t27.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	lr_end_transaction("MILARA_TC1_03_Search_Record",LR_AUTO);

	lr_think_time(4);
    web_add_header("AppD_Header", "MILARA_TC1_04_Record_Details");
	lr_start_transaction("MILARA_TC1_04_Record_Details");

	web_url("session.do_8", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?module=Licenses", 
		"Snapshot=t28.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CapTabSummary.do",
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capSearch.do?module=Licenses",
		"Snapshot=t29.inf",
		"Mode=HTML",
		LAST);

	web_submit_data("ajax.do",
		"Action=https://av-pt-ferrari.accela.com/portlets/i18n/ajax.do?mode=getDateFormat",
		"Method=POST",
		"TargetFrame=",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t30.inf",
		"Mode=HTML",
		ITEMDATA,
		LAST);

	web_submit_data("empty.jsp_4", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t31.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_url("blank.jsp_2",
		"URL=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/blank.jsp",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t32.inf",
		"Mode=HTML",
		LAST);

	web_custom_request("tabRecordCount.do",
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/tabRecordCount.do?module=Licenses&ID1=REC18&ID2=00000&ID3={Param_ID3}&xmlin=%3Croot%3E%3CcountID%3E5%3C/countID%3E%3CcountID%3E6%3C/countID%3E%3CcountID%3E2%3C/countID%3E%3CcountID%3E134%3C/countID%3E%3CcountID%3E16%3C/countID%3E%3CcountID%3E23%3C/countID%3E%3CcountID%3E415%3C/countID%3E%3CcountID%3E397%3C/countID%3E%3CcountID%3E456%3C/countID%3E%3CcountID%3E1%3C/countID%3E%3CcountID%3E378%3C/countID%3E%3CcountID%3E21%3C/countID%3E%3CcountID%3E226%3C/countID%3E%3CcountID%3E372%3C/countID%3E%3CcountID%3E24%3C/countID%3E%3CcountID%3E379%3C/countID%3E%3CcountID%3E10%3C/countID%3E%3CcountID%3E133%3C/countID%3E%3CcountID%3E17%3C/countID%3E%3CcountID%3E8%3C/countID%3E%3CcountID%3E19%3C/countID%3E%3CcountID%3E373%3C/countID%3E%3CcountID%3E14%3C/countID%3E%3CcountID%3E12%3C/countID%3E%3CcountID%3E13%3C/countID%3E%3CcountID%3E371%3C/countID%3E%3CcountID%3E27%3C/countID%3E%3CcountID%3E404%3C/countID%3E%3CcountID%3E360%3C/countID%3E%3CcountID%3E152%3C/countID%3E%3Ccount"
		"ID%3E303%3C/countID%3E%3CcountID%3E4%3C/countID%3E%3C/root%3E",
		"Method=GET",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/xml",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t33.inf",
		"Mode=HTML",
		"EncType=txt/xml",
		LAST);

	web_custom_request("search.do",
		"URL=https://av-pt-ferrari.accela.com/portlets/globalSearch/search.do?action=textResources",
		"Method=POST",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=application/x-json",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t34.inf",
		"Mode=HTML",
		"Body=categoryName=Portlet - Expression",
		LAST);

	web_custom_request("expression.do",
		"URL=https://av-pt-ferrari.accela.com/portlets/expression/expression.do?mode=getFields",
		"Method=POST",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t35.inf",
		"Mode=HTML",
		"Body=argumentPKs=%5B%7B%22portletID%22%3A-1%2C%22viewKey1%22%3A%22%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%2C%7B%22portletID%22%3A-2%2C%22viewKey1%22%3A%22NURSE%20SPECIALTY%20CERTIFICATION%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%2C%7B%22portletID%22%3A-2%2C%22viewKey1%22%3A%22NURSE%20SPECIALTY%20HISTORY%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%2C%7B%22portletID%22%3A-2%2C%22viewKey1%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%5D&expressionPageType=TABSUMMARY&isReload=false&module=Licenses&capType=Licenses%2FNursing%2FRegistered%20Nurse%2FLicense",
		LAST);

	web_custom_request("expression.do_2",
		"URL=https://av-pt-ferrari.accela.com/portlets/expression/expression.do?mode=execute",
		"Method=POST",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t36.inf",
		"Mode=HTML",
		"Body=value(FirstEntryURL)=%2Fportlets%2Fcap%2Fcapsummary%2FCapTabSummary.do%3Fmode%3DtabSummary%26isRedirect%3Dfalse%26module%3DLicenses&value(CurrentEntryURL)=%2Fportlets%2Fcap%2Fcapsummary%2FCapTabSummary.do%3Fmode%3DtabSummary%26isRedirect%3Dfalse%26module%3DLicenses&portlet_language=en_US&refresh_target=&refresh_url=&buttonName=&modeName=tabSummary&module=Licenses&itemName=&CurrentViewID=30046&exceptionLogID=&generalCAPSearch=&isGeneralCAP=Y&objectName=&CheckBoxName=&MaxNumber=&ExportFileType=print&CurrentViewID=30046&sessionIdFromWindow=lhOsuUEfqJyiZwzad17LYo1S&listID=&printType=&checkBoxValue=&expression_portlet_to_be_populate=-1&expression_portlet_to_be_populate=-99999&is_ASI_fields_displayed=true&expressionPageType=TABSUMMARY&expression_page_reload_after_submit_or_validate_failed=true&expression_portlet_to_be_populate=-2&expression_portlet_to_be_populate=-99999&valuetextarea999=%5B%7B%22values%22%3A%5B%7B%22Notification%20Template%22%3A%7B%22valueSeq%22%3A%22%22%2C%22value%22%3A%22MWBC%20Letter%22%2C"
		"%22rowIndex%22%3A%221%22%7D%2C%22Contact%20Type%22%3A%7B%22valueSeq%22%3A1%2C%22value%22%3A%22Applicant%22%2C%22rowIndex%22%3A%221%22%7D%2C%22Status%22%3A%7B%22valueSeq%22%3A2%2C%22value%22%3A%22Sent%22%2C%22rowIndex%22%3A%221%22%7D%2C%22Date%20Sent%22%3A%7B%22valueSeq%22%3A3%2C%22value%22%3A%2204%2F11%2F2018%22%2C%22rowIndex%22%3A%221%22%7D%2C%22Comments%22%3A%7B%22valueSeq%22%3A4%2C%22value%22%3A%22%22%2C%22rowIndex%22%3A%221%22%7D%7D%5D%2C%22group%22%3A%22NUR_RN_L%22%2C%22subgroup%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22templateType%22%3A%22Table%22%7D%2C%7B%22values%22%3A%5B%7B%22Obtained%20by%22%3A%7B%22valueSeq%22%3A%22%22%2C%22value%22%3A%22Endorsement%22%2C%22rowIndex%22%3A%221%22%7D%7D%5D%2C%22group%22%3A%22NUR_RN_L%22%2C%22subgroup%22%3A%22OBTAINDED%20BY%20METHOD%22%2C%22templateType%22%3A%22Form%22%7D%2C%7B%22values%22%3A%5B%7B%22Print%20Audit%20Number%22%3A%7B%22valueSeq%22%3A%22%22%2C%22value%22%3A%22%C2%A0%C2%A0%22%2C%22rowIndex%22%3A%221%22%7D%2C%22NCSBN%20ID%22%3A%7B%22valueSeq%22%3A%"
		"22%22%2C%22value%22%3A%22%C2%A0%C2%A0%22%2C%22rowIndex%22%3A%221%22%7D%7D%5D%2C%22group%22%3A%22NUR_RN_L%22%2C%22subgroup%22%3A%22INTERNAL%20USE%20ONLY%20L2K%20DATA%22%2C%22templateType%22%3A%22Form%22%7D%2C%7B%22values%22%3A%5B%7B%22Next%20Notification%20Date%22%3A%7B%22valueSeq%22%3A%22%22%2C%22value%22%3A%22%C2%A0%C2%A0%22%2C%22rowIndex%22%3A%221%22%7D%2C%22Next%20Notification%22%3A%7B%22valueSeq%22%3A%22%22%2C%22value%22%3A%22%C2%A0%C2%A0%22%2C%22rowIndex%22%3A%221%22%7D%7D%5D%2C%22group%22%3A%22NUR_RN_L%22%2C%22subgroup%22%3A%22RENEWAL%20INFO%22%2C%22templateType%22%3A%22Form%22%7D%5D&sourcetextarea999=%7B%22templateForms%22%3A%5B%7B%22groupName%22%3A%22NUR_RN_L%22%2C%22subgroups%22%3A%5B%7B%22displayName%22%3A%22Obtained%20By%20Method%22%2C%22readOnly%22%3Atrue%2C%22fields%22%3A%5B%7B%22fieldName%22%3A%22Obtained%20by%22%2C%22subgroupName%22%3A%22OBTAINDED%20BY%20METHOD%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22defaultValue%22%3A%22Endorsement%22%2C%22displayFieldName%22%3A%22Obtained%20by%22%2C%22di"
		"splayLen%22%3A0%2C%22displayOrder%22%3A10%2C%22fieldTypeValue%22%3A5%2C%22options%22%3A%7B%22target%22%3A%22_self%22%2C%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoForm.do%3Fmode%3Dview%26fromTab%3DY%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%3D{Param_ID3}%26fromTreeGrid%3DY%22%7D%2C%22checkboxDesc%22%3A%22Obtained%20by%22%2C%22checklistComment%22%3A%22Endorsement%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%5D%2C%22subgroupName%22%3A%22OBTAINDED%20BY%20METHOD%22%2C%22hasSelectCol%22%3Atrue%2C%22CSVData%22%3A%5B%5B%22Obtained%20by%22%5D%5D%2C%22rows%22%3Anull%7D%2C%7B%22displayName%22%3A%22RENEWAL%20INFO%22%2C%22readOnly%22%3Atrue%2C%22fields%22%3A%5B%7B%22fieldName%22%3A%22Next%20Notification%20Date%22%2C%22subgroupName%22%3A%22RENEWAL%20INFO%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22defaultValue%22%3A%22%C2%A0%C2%A0%22%2C%22displayFieldName%22%3A%22Next%20Notification%20Date%22%2C%22displayLen%22%3A0%2C%22displayOrder%22%3A"
		"10%2C%22fieldTypeValue%22%3A2%2C%22options%22%3A%7B%22target%22%3A%22_self%22%2C%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoForm.do%3Fmode%3Dview%26fromTab%3DY%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%3D{Param_ID3}%26fromTreeGrid%3DY%22%7D%2C%22checkboxDesc%22%3A%22Next%20Notification%20Date%22%2C%22checklistComment%22%3A%22%C2%A0%C2%A0%22%2C%22checkboxInd%22%3A%222%22%2C%22fieldTypeEnum%22%3A%22Date%22%7D%2C%7B%22fieldName%22%3A%22Next%20Notification%22%2C%22subgroupName%22%3A%22RENEWAL%20INFO%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22defaultValue%22%3A%22%C2%A0%C2%A0%22%2C%22displayFieldName%22%3A%22Next%20Notification%22%2C%22displayLen%22%3A0%2C%22displayOrder%22%3A20%2C%22fieldTypeValue%22%3A5%2C%22options%22%3A%7B%22target%22%3A%22_self%22%2C%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoForm.do%3Fmode%3Dview%26fromTab%3DY%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%3D{Param_ID3}%26fromTreeGrid%3DY"
		"%22%7D%2C%22checkboxDesc%22%3A%22Next%20Notification%22%2C%22checklistComment%22%3A%22%C2%A0%C2%A0%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%5D%2C%22subgroupName%22%3A%22RENEWAL%20INFO%22%2C%22hasSelectCol%22%3Atrue%2C%22CSVData%22%3A%5B%5B%22Next%20Notification%20Date%22%2C%22Next%20Notification%22%5D%5D%2C%22rows%22%3Anull%7D%2C%7B%22displayName%22%3A%22Internal%20Use%20Only%20L2K%20Data%22%2C%22readOnly%22%3Atrue%2C%22fields%22%3A%5B%7B%22fieldName%22%3A%22Print%20Audit%20Number%22%2C%22subgroupName%22%3A%22INTERNAL%20USE%20ONLY%20L2K%20DATA%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22defaultValue%22%3A%22%C2%A0%C2%A0%22%2C%22displayFieldName%22%3A%22Print%20Audit%20Number%22%2C%22displayLen%22%3A0%2C%22displayOrder%22%3A10%2C%22fieldTypeValue%22%3A4%2C%22options%22%3A%7B%22target%22%3A%22_self%22%2C%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoForm.do%3Fmode%3Dview%26fromTab%3DY%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%"
		"3D{Param_ID3}%26fromTreeGrid%3DY%22%7D%2C%22checkboxDesc%22%3A%22Print%20Audit%20Number%22%2C%22checklistComment%22%3A%22%C2%A0%C2%A0%22%2C%22checkboxInd%22%3A%224%22%2C%22fieldTypeEnum%22%3A%22Number%22%7D%2C%7B%22fieldName%22%3A%22NCSBN%20ID%22%2C%22subgroupName%22%3A%22INTERNAL%20USE%20ONLY%20L2K%20DATA%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22defaultValue%22%3A%22%C2%A0%C2%A0%22%2C%22displayFieldName%22%3A%22NCSBN%20ID%22%2C%22displayLen%22%3A0%2C%22displayOrder%22%3A20%2C%22fieldTypeValue%22%3A4%2C%22options%22%3A%7B%22target%22%3A%22_self%22%2C%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoForm.do%3Fmode%3Dview%26fromTab%3DY%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%3D{Param_ID3}%26fromTreeGrid%3DY%22%7D%2C%22checkboxDesc%22%3A%22NCSBN%20ID%22%2C%22checklistComment%22%3A%22%C2%A0%C2%A0%22%2C%22checkboxInd%22%3A%224%22%2C%22fieldTypeEnum%22%3A%22Number%22%7D%5D%2C%22subgroupName%22%3A%22INTERNAL%20USE%20ONLY%20L2K%20DATA%22%2C%22hasSelectCol%22%3Atru"
		"e%2C%22CSVData%22%3A%5B%5B%22Print%20Audit%20Number%22%2C%22NCSBN%20ID%22%5D%5D%2C%22rows%22%3Anull%7D%5D%2C%22templateType%22%3A%22Form%22%2C%22readOnly%22%3Atrue%7D%5D%2C%22templateTables%22%3A%5B%7B%22groupName%22%3A%22NUR_RN_L%22%2C%22subgroups%22%3A%5B%7B%22displayName%22%3A%22Nurse%20Specialty%20Certification%22%2C%22rows%22%3Anull%2C%22readOnly%22%3Atrue%2C%22fields%22%3A%5B%7B%22fieldName%22%3A%22Specialty%20Certification%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20CERTIFICATION%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Specialty%20Certification%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A5%2C%22fieldTypeValue%22%3A5%2C%22readOnly%22%3Atrue%2C%22options%22%3A%7B%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoTableForm.do%3Fmode%3Dlist%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%3D{Param_ID3}%26fromTreeGrid%3DY%26tableName%3DNUR_RN_L%3A%3ANURSE%2BSPECIALTY%2BCERTIFICATION%22%2C%22target%22%3A%22_self%22%7D%2C%22check"
		"boxDesc%22%3A%22Specialty%20Certification%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%2C%7B%22fieldName%22%3A%22Status%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20CERTIFICATION%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Status%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A10%2C%22fieldTypeValue%22%3A5%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Status%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%2C%7B%22fieldName%22%3A%22Issue%20Date%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20CERTIFICATION%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Issue%20Date%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A15%2C%22fieldTypeValue%22%3A2%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Issue%20Date%22%2C%22checkboxInd%22%3A%222%22%2C%22fieldTypeEnum%22%3A%22Date%22%7D%2C%7B%22fieldName%22%3A%22Expiration%20Date%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20CERTIFICATION%22%2C%22groupName%"
		"22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Expiration%20Date%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A20%2C%22fieldTypeValue%22%3A2%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Expiration%20Date%22%2C%22checkboxInd%22%3A%222%22%2C%22fieldTypeEnum%22%3A%22Date%22%7D%5D%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20CERTIFICATION%22%2C%22hasSelectCol%22%3Afalse%2C%22CSVData%22%3A%5B%5B%22Specialty%20Certification%22%2C%22Status%22%2C%22Issue%20Date%22%2C%22Expiration%20Date%22%5D%5D%7D%2C%7B%22displayName%22%3A%22Nurse%20Specialty%20History%22%2C%22rows%22%3Anull%2C%22readOnly%22%3Atrue%2C%22fields%22%3A%5B%7B%22fieldName%22%3A%22Specialty%20Certification%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20HISTORY%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Specialty%20Certification%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A10%2C%22fieldTypeValue%22%3A5%2C%22readOnly%22%3Atrue%2C%22options%22%3A%7B%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoTableForm"
		".do%3Fmode%3Dlist%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%3D{Param_ID3}%26fromTreeGrid%3DY%26tableName%3DNUR_RN_L%3A%3ANURSE%2BSPECIALTY%2BHISTORY%22%2C%22target%22%3A%22_self%22%7D%2C%22checkboxDesc%22%3A%22Specialty%20Certification%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%2C%7B%22fieldName%22%3A%22Date%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20HISTORY%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Date%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A20%2C%22fieldTypeValue%22%3A2%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Date%22%2C%22checkboxInd%22%3A%222%22%2C%22fieldTypeEnum%22%3A%22Date%22%7D%2C%7B%22fieldName%22%3A%22Specialty%20Status%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20HISTORY%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Specialty%20Status%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A30%2C%22fieldTypeValue%22%3A5%2C%22readOnly%22%3Atrue%2C%22che"
		"ckboxDesc%22%3A%22Specialty%20Status%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%2C%7B%22fieldName%22%3A%22Change%20Reason%22%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20HISTORY%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Change%20Reason%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A40%2C%22fieldTypeValue%22%3A6%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Change%20Reason%22%2C%22checkboxInd%22%3A%226%22%2C%22fieldTypeEnum%22%3A%22Textarea%22%7D%5D%2C%22subgroupName%22%3A%22NURSE%20SPECIALTY%20HISTORY%22%2C%22hasSelectCol%22%3Afalse%2C%22CSVData%22%3A%5B%5B%22Specialty%20Certification%22%2C%22Date%22%2C%22Specialty%20Status%22%2C%22Change%20Reason%22%5D%5D%7D%2C%7B%22displayName%22%3A%22Notification%20Generator%22%2C%22rows%22%3Anull%2C%22readOnly%22%3Atrue%2C%22fields%22%3A%5B%7B%22fieldName%22%3A%22Notification%20Template%22%2C%22subgroupName%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%"
		"22%3A%22Notification%20Template%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A10%2C%22fieldTypeValue%22%3A5%2C%22readOnly%22%3Atrue%2C%22options%22%3A%7B%22link%22%3A%22%2Fportlets%2Fappspecinfo%2FappSpecInfoTableForm.do%3Fmode%3Dlist%26module%3DLicenses%26serviceProviderCode%3DMILARA%26ID1%3DREC18%26ID2%3D00000%26ID3%3D{Param_ID3}%26fromTreeGrid%3DY%26tableName%3DNUR_RN_L%3A%3ANOTIFICATION%2BGENERATOR%2BLIC%22%2C%22target%22%3A%22_self%22%7D%2C%22checkboxDesc%22%3A%22Notification%20Template%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%2C%7B%22fieldName%22%3A%22Contact%20Type%22%2C%22subgroupName%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Contact%20Type%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A15%2C%22fieldTypeValue%22%3A5%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Contact%20Type%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%2C%7B%22fieldName%22%3A%22Status%22%2C%22s"
		"ubgroupName%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Status%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A20%2C%22fieldTypeValue%22%3A5%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Status%22%2C%22checkboxInd%22%3A%225%22%2C%22fieldTypeEnum%22%3A%22Dropdown%22%7D%2C%7B%22fieldName%22%3A%22Date%20Sent%22%2C%22subgroupName%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Date%20Sent%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A30%2C%22fieldTypeValue%22%3A2%2C%22readOnly%22%3Atrue%2C%22checkboxDesc%22%3A%22Date%20Sent%22%2C%22checkboxInd%22%3A%222%22%2C%22fieldTypeEnum%22%3A%22Date%22%7D%2C%7B%22fieldName%22%3A%22Comments%22%2C%22subgroupName%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22groupName%22%3A%22NUR_RN_L%22%2C%22displayFieldName%22%3A%22Comments%22%2C%22displayLen%22%3A-1%2C%22displayOrder%22%3A40%2C%22fieldTypeValue%22%3A6%2C%22readOnly%22%3Atrue%2C%22checkboxDesc"
		"%22%3A%22Comments%22%2C%22checkboxInd%22%3A%226%22%2C%22fieldTypeEnum%22%3A%22Textarea%22%7D%5D%2C%22subgroupName%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22hasSelectCol%22%3Afalse%2C%22CSVData%22%3A%5B%5B%22Notification%20Template%22%2C%22Contact%20Type%22%2C%22Status%22%2C%22Date%20Sent%22%2C%22Comments%22%5D%2C%5B%22MWBC%20Letter%22%2C%22Applicant%22%2C%22Sent%22%2C%2204%2F11%2F2018%22%2Cnull%5D%5D%7D%5D%2C%22templateType%22%3A%22Table%22%2C%22readOnly%22%3Atrue%7D%5D%2C%22readOnly%22%3Atrue%2C%22UIUID%22%3A999%7D&layouttextarea999=%7B%22map%22%3A%7B%7D%2C%22layouts%22%3A%5B%5D%2C%22layoutHtml%22%3A%22%22%7D&uiuid=999&accelasubmitbuttonname=Previous&callBack=&variableKey=onLoad&refAPONumber=undefined&argumentPKs=%5B%7B%22portletID%22%3A-1%2C%22viewKey1%22%3A%22%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%2C%7B%22portletID%22%3A-2%2C%22viewKey1%22%3A%22NURSE%20SPECIALTY%20CERTIFICATION%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%2C%7B%22portletID%22%3A-2%2C%22viewKey1%22%3A"
		"%22NURSE%20SPECIALTY%20HISTORY%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%2C%7B%22portletID%22%3A-2%2C%22viewKey1%22%3A%22NOTIFICATION%20GENERATOR%20LIC%22%2C%22viewKey2%22%3A%22%22%2C%22viewKey3%22%3A%22%22%7D%5D&expressionPageType=TABSUMMARY&mode=execute",
		LAST);

	lr_end_transaction("MILARA_TC1_04_Record_Details",LR_AUTO);

	lr_think_time(4);
    web_add_header("AppD_Header", "MILARA_TC1_05_Click_Addtl_Info");
	lr_start_transaction("MILARA_TC1_05_Click_Addtl_Info");

	web_url("session.do_12",
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=application/json",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t40.inf",
		"Mode=HTML",
		LAST);

	web_url("addtInfoForm.do",
		"URL=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?mode=view&module=Licenses",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/portlets/cap/capsummary/CapTabSummary.do?mode=tabSummary&serviceProviderCode=MILARA&ID1=REC18&ID2=00000&ID3={Param_ID3}&requireNotice=YES&clearForm=clearForm&module=Licenses&isFromCapList=true&isGeneralCAP=Y",
		"Snapshot=t41.inf",
		"Mode=HTML",
		LAST);

	web_submit_data("empty.jsp_5", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t42.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_custom_request("tabRecordCount.do_2",
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/tabRecordCount.do?module=Licenses&ID1=REC18&ID2=00000&ID3={Param_ID3}&xmlin=%3Croot%3E%3CcountID%3E5%3C/countID%3E%3CcountID%3E6%3C/countID%3E%3CcountID%3E2%3C/countID%3E%3CcountID%3E134%3C/countID%3E%3CcountID%3E16%3C/countID%3E%3CcountID%3E23%3C/countID%3E%3CcountID%3E415%3C/countID%3E%3CcountID%3E397%3C/countID%3E%3CcountID%3E456%3C/countID%3E%3CcountID%3E1%3C/countID%3E%3CcountID%3E378%3C/countID%3E%3CcountID%3E21%3C/countID%3E%3CcountID%3E226%3C/countID%3E%3CcountID%3E372%3C/countID%3E%3CcountID%3E24%3C/countID%3E%3CcountID%3E379%3C/countID%3E%3CcountID%3E10%3C/countID%3E%3CcountID%3E133%3C/countID%3E%3CcountID%3E17%3C/countID%3E%3CcountID%3E8%3C/countID%3E%3CcountID%3E19%3C/countID%3E%3CcountID%3E373%3C/countID%3E%3CcountID%3E14%3C/countID%3E%3CcountID%3E12%3C/countID%3E%3CcountID%3E13%3C/countID%3E%3CcountID%3E371%3C/countID%3E%3CcountID%3E27%3C/countID%3E%3CcountID%3E404%3C/countID%3E%3CcountID%3E360%3C/countID%3E%3CcountID%3E152%3C/countID%3E%3Ccount"
		"ID%3E303%3C/countID%3E%3CcountID%3E4%3C/countID%3E%3C/root%3E",
		"Method=GET",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/xml",
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?mode=view&module=Licenses",
		"Snapshot=t43.inf",
		"Mode=HTML",
		"EncType=txt/xml",
		LAST);

	lr_end_transaction("MILARA_TC1_05_Click_Addtl_Info",LR_AUTO);

	lr_think_time(4);
    web_add_header("AppD_Header", "MILARA_TC1_06_Save_Addtl_Info");
	lr_start_transaction("MILARA_TC1_06_Save_Addtl_Info");

	web_url("session.do_13", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?mode=view&module=Licenses", 
		"Snapshot=t44.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("addtInfoForm.do_2",
		"Action=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?module=Licenses",
		"Method=POST",
		"TargetFrame=",
		"RecContentType=text/html",
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?mode=view&module=Licenses",
		"Snapshot=t45.inf",
		"Mode=HTML",
		ITEMDATA,
		"Name=value(FirstEntryURL)", "Value=/portlets/addtinfo/addtInfoForm.do?mode=view&module=Licenses", ENDITEM,
		"Name=value(CurrentEntryURL)", "Value=/portlets/addtinfo/addtInfoForm.do?mode=view&module=Licenses", ENDITEM,
		"Name=portlet_language", "Value=en_US", ENDITEM,
		"Name=refresh_target", "Value=", ENDITEM,
		"Name=refresh_url", "Value=", ENDITEM,
		"Name=buttonName", "Value=", ENDITEM,
		"Name=modeName", "Value=view", ENDITEM,
		"Name=module", "Value=Licenses", ENDITEM,
		"Name=accelasubmitbuttonname", "Value=Save", ENDITEM,
		"Name=itemName", "Value=", ENDITEM,
		"Name=CurrentViewID", "Value=21031", ENDITEM,
		"Name=exceptionLogID", "Value=", ENDITEM,
		"Name=generalCAPSearch", "Value=", ENDITEM,
		"Name=objectName", "Value=", ENDITEM,
		"Name=CheckBoxName", "Value=", ENDITEM,
		"Name=MaxNumber", "Value=", ENDITEM,
		"Name=ExportFileType", "Value=print", ENDITEM,
		"Name=CurrentViewID", "Value=21031", ENDITEM,
		"Name=sessionIdFromWindow", "Value=lhOsuUEfqJyiZwzad17LYo1S", ENDITEM,
		"Name=listID", "Value=", ENDITEM,
		"Name=printType", "Value=", ENDITEM,
		"Name=checkBoxValue", "Value=", ENDITEM,
		"Name=value(capID*ID1)", "Value=REC18", ENDITEM,
		"Name=value(capID*ID2)", "Value=00000", ENDITEM,
		"Name=value(capID*ID3)", "Value={Param_ID3}", ENDITEM,
		"Name=value(bValuatnModel*estimatedValue)", "Value=1", ENDITEM,
		"Name=value(capDetailModel*buildingCount)", "Value=1", ENDITEM,
		"Name=value(capDetailModel*houseCount)", "Value=1", ENDITEM,
		"Name=value(capDetailModel*constTypeCode)", "Value=", ENDITEM,
		"Name=value(capDetailModel*publicOwned)", "Value=N", ENDITEM,
		LAST);

	web_url("EMSEMessage.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/emse/EMSEMessage.do?module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?module=Licenses", 
		"Snapshot=t46.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("empty.jsp_6", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t47.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_custom_request("tabRecordCount.do_3",
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/tabRecordCount.do?module=Licenses&ID1=REC18&ID2=00000&ID3={Param_ID3}&xmlin=%3Croot%3E%3CcountID%3E5%3C/countID%3E%3CcountID%3E6%3C/countID%3E%3CcountID%3E2%3C/countID%3E%3CcountID%3E134%3C/countID%3E%3CcountID%3E16%3C/countID%3E%3CcountID%3E23%3C/countID%3E%3CcountID%3E415%3C/countID%3E%3CcountID%3E397%3C/countID%3E%3CcountID%3E456%3C/countID%3E%3CcountID%3E1%3C/countID%3E%3CcountID%3E378%3C/countID%3E%3CcountID%3E21%3C/countID%3E%3CcountID%3E226%3C/countID%3E%3CcountID%3E372%3C/countID%3E%3CcountID%3E24%3C/countID%3E%3CcountID%3E379%3C/countID%3E%3CcountID%3E10%3C/countID%3E%3CcountID%3E133%3C/countID%3E%3CcountID%3E17%3C/countID%3E%3CcountID%3E8%3C/countID%3E%3CcountID%3E19%3C/countID%3E%3CcountID%3E373%3C/countID%3E%3CcountID%3E14%3C/countID%3E%3CcountID%3E12%3C/countID%3E%3CcountID%3E13%3C/countID%3E%3CcountID%3E371%3C/countID%3E%3CcountID%3E27%3C/countID%3E%3CcountID%3E404%3C/countID%3E%3CcountID%3E360%3C/countID%3E%3CcountID%3E152%3C/countID%3E%3Ccount"
		"ID%3E303%3C/countID%3E%3CcountID%3E4%3C/countID%3E%3C/root%3E",
		"Method=GET",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/xml",
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?module=Licenses",
		"Snapshot=t48.inf",
		"Mode=HTML",
		"EncType=txt/xml",
		LAST);

	web_submit_data("empty.jsp_7", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/emse/EMSEMessage.do?module=Licenses", 
		"Snapshot=t49.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_url("session.do_14", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?module=Licenses", 
		"Snapshot=t50.inf", 
		"Mode=HTML", 
		LAST);

	lr_end_transaction("MILARA_TC1_06_Save_Addtl_Info",LR_AUTO);
    web_add_header("AppD_Header", "MILARA_TC1_07_Click_RecordHistory");
	lr_start_transaction("MILARA_TC1_07_Click_RecordHistory");

	web_url("session.do_15", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?module=Licenses", 
		"Snapshot=t51.inf", 
		"Mode=HTML", 
		LAST);

	web_url("recordActivityReport.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/commons/communication/recordActivity/recordActivityReport.do?mode=list&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/addtinfo/addtInfoForm.do?module=Licenses", 
		"Snapshot=t52.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("empty.jsp_8", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t53.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_custom_request("tabRecordCount.do_4",
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/tabRecordCount.do?module=Licenses&ID1=REC18&ID2=00000&ID3={Param_ID3}&xmlin=%3Croot%3E%3CcountID%3E5%3C/countID%3E%3CcountID%3E6%3C/countID%3E%3CcountID%3E2%3C/countID%3E%3CcountID%3E134%3C/countID%3E%3CcountID%3E16%3C/countID%3E%3CcountID%3E23%3C/countID%3E%3CcountID%3E415%3C/countID%3E%3CcountID%3E397%3C/countID%3E%3CcountID%3E456%3C/countID%3E%3CcountID%3E1%3C/countID%3E%3CcountID%3E378%3C/countID%3E%3CcountID%3E21%3C/countID%3E%3CcountID%3E226%3C/countID%3E%3CcountID%3E372%3C/countID%3E%3CcountID%3E24%3C/countID%3E%3CcountID%3E379%3C/countID%3E%3CcountID%3E10%3C/countID%3E%3CcountID%3E133%3C/countID%3E%3CcountID%3E17%3C/countID%3E%3CcountID%3E8%3C/countID%3E%3CcountID%3E19%3C/countID%3E%3CcountID%3E373%3C/countID%3E%3CcountID%3E14%3C/countID%3E%3CcountID%3E12%3C/countID%3E%3CcountID%3E13%3C/countID%3E%3CcountID%3E371%3C/countID%3E%3CcountID%3E27%3C/countID%3E%3CcountID%3E404%3C/countID%3E%3CcountID%3E360%3C/countID%3E%3CcountID%3E152%3C/countID%3E%3Ccount"
		"ID%3E303%3C/countID%3E%3CcountID%3E4%3C/countID%3E%3C/root%3E",
		"Method=GET",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/xml",
		"Referer=https://av-pt-ferrari.accela.com/portlets/commons/communication/recordActivity/recordActivityReport.do?mode=list&module=Licenses",
		"Snapshot=t54.inf",
		"Mode=HTML",
		"EncType=txt/xml",
		LAST);

	lr_end_transaction("MILARA_TC1_07_Click_RecordHistory",LR_AUTO);

	lr_think_time(4);
    web_add_header("AppD_Header", "MILARA_TC1_08_Click_WorkFlow");
	lr_start_transaction("MILARA_TC1_08_Click_WorkFlow");

	web_url("session.do_16", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/commons/communication/recordActivity/recordActivityReport.do?mode=list&module=Licenses", 
		"Snapshot=t55.inf", 
		"Mode=HTML", 
		LAST);

	web_url("workflowStatusList.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/workflow/workflowStatusList.do?module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/commons/communication/recordActivity/recordActivityReport.do?mode=list&module=Licenses", 
		"Snapshot=t56.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("empty.jsp_9", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t57.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_custom_request("text.do_2", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/text.do?mode=localizedText", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/workflow/workflowStatusList.do?module=Licenses", 
		"Snapshot=t58.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={\"AANewUX_WorkFlow_Assigned\":\"\",\"AANewUX_WorkFlow_Started\":\"\",\"AANewUX_WorkFlow_Save\":\"\",\"AANewUX_WorkFlow_Cancel\":\"\",\"AANewUX_WorkFlow_ShowAll\":\"\",\"AANewUX_WorkFlow_By\":\"\",\"AANewUX_WorkFlow_Due\":\"\",\"AANewUX_WorkFlow_Subtask\":\"\",\"AANewUX_WorkFlow_NewAdhocTask\":\"\",\"AANewUX_WorkFlow_AdditionalAdhocTask\":\"\",\"AANewUX_WorkFlow_WorkflowTask\":\"\",\"AANewUX_WorkFlow_BucketCompleted\":\"\",\"AANewUX_WorkFlow_BucketInprogress\":\"\",\""
		"AANewUX_WorkFlow_BucketUpNext\":\"\",\"AANewUX_WorkFlow_TaskInactive\":\"\",\"AANewUX_WorkFlow_TaskInprogress\":\"\",\"AANewUX_WorkFlow_TaskComplete\":\"\",\"AANewUX_WorkFlow_ViewHistory\":\"\",\"AANewUX_WorkFlow_ViewWorkflowDesign\":\"\",\"AANewUX_WorkFlow_IncludeAddPage\":\"\",\"AANewUX_WorkFlow_PageOf\":\"\",\"AANewUX_WorkFlow_PageCompleted\":\"\",\"AANewUX_WorkFlow_WorkflowDesign\":\"\",\"AANewUX_Designer_NewDesigner\":\"\",\"AANewUX_Designer_OldDesigner\":\"\",\"AANewUX_Designer_Preview\":\""
		"\",\"AANewUX_Designer_Text\":\"\",\"AANewUX_Designer_Controls\":\"\",\"AANewUX_Designer_NoCtlAvailable\":\"\",\"AANewUX_Designer_Drag\":\"\",\"AANewUX_Designer_Select\":\"\",\"AANewUX_Designer_Properties\":\"\",\"AANewUX_Designer_Ok\":\"\",\"AANewUX_Designer_Label\":\"\",\"AANewUX_Designer_Url\":\"\",\"AANewUX_Designer_Save\":\"\",\"AANewUX_Designer_Cancel\":\"\",\"AANewUX_Designer_DynamicLabelText\":\"\",\"AANewUX_CheckList_SaveAll\":\"\"}", 
		LAST);

	web_url("workflow.do", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/workflow.do?mode=getTasks&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/workflow/workflowStatusList.do?module=Licenses", 
		"Snapshot=t59.inf", 
		"Mode=HTML", 
		LAST);

	web_url("workflow.do_2", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/workflow.do?mode=viewWorkFlowDesignPermission&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/workflow/workflowStatusList.do?module=Licenses", 
		"Snapshot=t60.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("empty.jsp_10", 
		"Action=https://av-pt-ferrari.accela.com/portlets/framework/includes/error/empty.jsp", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t61.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_url("session.do_17", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/workflow/workflowStatusList.do?module=Licenses", 
		"Snapshot=t62.inf", 
		"Mode=HTML", 
		LAST);

	web_custom_request("tabRecordCount.do_5",
		"URL=https://av-pt-ferrari.accela.com/portlets/cap/tabRecordCount.do?module=Licenses&ID1=REC18&ID2=00000&ID3={Param_ID3}&xmlin=%3Croot%3E%3CcountID%3E5%3C/countID%3E%3CcountID%3E6%3C/countID%3E%3CcountID%3E2%3C/countID%3E%3CcountID%3E134%3C/countID%3E%3CcountID%3E16%3C/countID%3E%3CcountID%3E23%3C/countID%3E%3CcountID%3E415%3C/countID%3E%3CcountID%3E397%3C/countID%3E%3CcountID%3E456%3C/countID%3E%3CcountID%3E1%3C/countID%3E%3CcountID%3E378%3C/countID%3E%3CcountID%3E21%3C/countID%3E%3CcountID%3E226%3C/countID%3E%3CcountID%3E372%3C/countID%3E%3CcountID%3E24%3C/countID%3E%3CcountID%3E379%3C/countID%3E%3CcountID%3E10%3C/countID%3E%3CcountID%3E133%3C/countID%3E%3CcountID%3E17%3C/countID%3E%3CcountID%3E8%3C/countID%3E%3CcountID%3E19%3C/countID%3E%3CcountID%3E373%3C/countID%3E%3CcountID%3E14%3C/countID%3E%3CcountID%3E12%3C/countID%3E%3CcountID%3E13%3C/countID%3E%3CcountID%3E371%3C/countID%3E%3CcountID%3E27%3C/countID%3E%3CcountID%3E404%3C/countID%3E%3CcountID%3E360%3C/countID%3E%3CcountID%3E152%3C/countID%3E%3Ccount"
		"ID%3E303%3C/countID%3E%3CcountID%3E4%3C/countID%3E%3C/root%3E",
		"Method=GET",
		"TargetFrame=",
		"Resource=0",
		"RecContentType=text/xml",
		"Referer=https://av-pt-ferrari.accela.com/portlets/workflow/workflowStatusList.do?module=Licenses",
		"Snapshot=t63.inf",
		"Mode=HTML",
		"EncType=txt/xml",
		LAST);

	lr_end_transaction("MILARA_TC1_08_Click_WorkFlow",LR_AUTO);

	lr_think_time(8);
    web_add_header("AppD_Header", "MILARA_SignOut");
	lr_start_transaction("MILARA_SignOut");

	web_url("session.do_18", 
		"URL=https://av-pt-ferrari.accela.com/portlets/spa/session.do?mode=activateSpace&spaceName=spaces.b08e1&module=Licenses", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/workflow/workflowStatusList.do?module=Licenses", 
		"Snapshot=t64.inf", 
		"Mode=HTML", 
		LAST);

	lr_think_time(4);

	web_url("signoff.do", 
		"URL=https://av-pt-ferrari.accela.com/security/signoff.do", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/portlets/spa/dashboard.do", 
		"Snapshot=t65.inf", 
		"Mode=HTML", 
		LAST);

	web_submit_data("portal", 
		"Action=https://av-pt-ferrari.accela.com/jetspeed/portal?action=JClearCookie", 
		"Method=POST", 
		"TargetFrame=", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/security/signoff.do", 
		"Snapshot=t66.inf", 
		"Mode=HTML", 
		ITEMDATA, 
		LAST);

	web_url("logoutAction.do", 
		"URL=https://av-pt-ferrari.accela.com/ssoAdapter/logoutAction.do?servProvCode=MILARA&successURL=%2Fsecurity%2FhostSignon.do%3FsignOff%3Dtrue", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/security/signoff.do", 
		"Snapshot=t67.inf", 
		"Mode=HTML", 
		LAST);

	web_url("hostSignon.do_3", 
		"URL=https://av-pt-ferrari.accela.com/security/hostSignon.do?signOff=true", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://av-pt-ferrari.accela.com/ssoAdapter/logoutAction.do?servProvCode=MILARA&successURL=%2Fsecurity%2FhostSignon.do%3FsignOff%3Dtrue", 
		"Snapshot=t68.inf", 
		"Mode=HTML", 
		LAST);

	lr_end_transaction("MILARA_SignOut",LR_AUTO);

	return 0;
}